// @ts-nocheck
/**
 * OpenAI Fact Ledger — Orchestrator
 *
 * runOpenAIFactLedgerPipeline() is the openai_fact_ledger counterpart to
 * pipeline.ts's runExtractionPipeline() and MUST return the exact same
 * ExtractionPipelineResult shape ({rows, method, warnings, validationErrors,
 * metadata}), with metadata.extractionDebug.merged_field_sources /
 * .validated_field_values in the same per-field {value, source, confidence,
 * source_text, source_page} shape pipeline.ts's snapshotFieldMap() produces
 * (reused here, not reimplemented) — this is the contract that lets every
 * downstream consumer (buildMinimalReviewPayload, buildReviewPayload,
 * LeaseReview.jsx) work unchanged regardless of which provider ran.
 *
 * Prefers Azure canonical text extraction (input.docling, built upstream
 * from the Azure-parsed docling_raw) over file-mode OpenAI calls — file mode
 * is only reachable through fact-ledger-extractor.ts's own opt-in flag.
 *
 * On any internal failure this degrades to {rows:[], method:"fallback", ...}
 * rather than throwing, exactly like runExtractionPipeline() does for
 * too-short documents.
 */

import type { DoclingOutput, ExtractionPipelineResult } from "../types.ts";
import { parseDocument } from "../parser.ts";
import { flattenRecords } from "../validator.ts";
import { computeDerivedFields } from "../calculator.ts";
import { snapshotFieldMap } from "../pipeline.ts";
import { resolveDocumentIndex, enrichFactWithBlockEvidence } from "./document-index-v3.ts";
import { classifyDocumentProfile } from "./profile-classifier.ts";
import { extractFactLedger } from "./fact-ledger-extractor.ts";
import { extractFactLedgerAdaptive } from "./adaptive-extractor.ts";

// Section-Aware Candidate Router: ON by default (the whole point is real
// cost/accuracy behavior change, not another opt-in side-write sitting next
// to document-intelligence-v3). DISABLE_ADAPTIVE_FACT_LEDGER_EXTRACTION is an
// explicit, fast operator kill switch (no code deploy needed) back to the
// original whole-document chunking path, for exactly the situations this
// sandboxed session cannot itself validate against (real Azure/OpenAI
// traffic). extractFactLedgerAdaptive() itself also falls back to
// extractFactLedger() per-document whenever adaptive routing cannot
// confidently apply (no text blocks, resume requested, file-mode requested)
// -- this flag is a coarser, whole-deployment override on top of that
// per-document safety net.
function adaptiveExtractionDisabled(): boolean {
  try {
    return String(Deno.env.get("DISABLE_ADAPTIVE_FACT_LEDGER_EXTRACTION") || "").toLowerCase() === "true";
  } catch {
    return false;
  }
}
import { mapFactsToStandardFields } from "./fact-field-mapper.ts";
import { surfaceDynamicFacts, rescueNearMissedFacts } from "./dynamic-fact-surfacer.ts";
import { computeProfileApprovalBlockers } from "./approval-blockers.ts";
import type { OpenAIFactLedgerInput, OpenAIFactLedgerOptions } from "./types.ts";
import { LLMProviderError } from "../../llm.ts";
import { EXTRACTION_CONTRACT_VERSION } from "../contract-version.ts";


function emptyMetadata(processingTimeMs: number) {
  return {
    ruleFieldsExtracted: 0,
    tableFieldsExtracted: 0,
    llmFieldsExtracted: 0,
    totalRecords: 0,
    avgConfidence: 0,
    chunksProcessed: 0,
    processingTimeMs,
  };
}

function withOpenAIFactLedgerDebug<T extends ExtractionPipelineResult>(result: T): T {
  const debug = (result.metadata as any)?.extractionDebug;
  if (debug && typeof debug === "object") {
    if (debug.openai_fact_ledger && !debug.vertex_fact_ledger) {
      debug.vertex_fact_ledger = debug.openai_fact_ledger;
    }
    if (debug.vertex_fact_ledger && !debug.openai_fact_ledger) {
      debug.openai_fact_ledger = debug.vertex_fact_ledger;
    }
    if (debug.extraction_contract_version === "vertex-fact-ledger-v1" || debug.extraction_contract_version === "openai-fact-ledger-v1") {
      debug.legacy_extraction_contract_version = debug.extraction_contract_version;
      // src/lib/leaseReviewSchema.js's CURRENT_EXTRACTION_CONTRACT_VERSION
      // staleness check (LeaseReview.jsx's isStalePayload) compares against
      // the SHARED contract-version.ts constant every other extraction path
      // (ingest-file, normalize-pdf-output, pipeline.ts) already uses. This
      // module's own provider-specific tag ("openai-fact-ledger-v1", and
      // before it "vertex-fact-ledger-v1") never matched that shared value,
      // so the UI marked every openai_fact_ledger extraction "generated by
      // an older extractor" regardless of actual freshness -- this is that
      // fix, not a version bump (the payload shape is unchanged).
      debug.extraction_contract_version = EXTRACTION_CONTRACT_VERSION;
    }
  }
  return result;
}
function fallbackResult(
  warning: string,
  startTime: number,
  failureClassification?: string,
  failureHttpStatus?: number,
  indexSource?: string,
  fallbackReason?: string | null,
  failureProviderErrorCode?: string,
  failureRequestId?: string,
  failureRequestUrl?: string,
): ExtractionPipelineResult {
  return withOpenAIFactLedgerDebug({
    rows: [],
    method: "fallback",
    warnings: [warning],
    validationErrors: [],
    metadata: {
      ...emptyMetadata(Date.now() - startTime),
      // Azure+OpenAI Phase 4E: structured, not string-parsed, failure signal
      // for the business-extraction acceptance/fallback-eligibility layer.
      extractionDebug: {
        openai_fact_ledger: {
          failure_classification: failureClassification ?? "unknown",
          failure_http_status: failureHttpStatus ?? null,
          // Provider's own error code, request ID, and the exact request URL
          // (no secrets) — see the same fields on fact-ledger-extractor.ts's
          // FactLedgerResult for why these matter more than the HTTP status
          // alone when diagnosing a wrong endpoint/deployment/api-version.
          failure_provider_error_code: failureProviderErrorCode ?? null,
          failure_request_id: failureRequestId ?? null,
          failure_request_url: failureRequestUrl ?? null,
          document_index_source: indexSource,
          document_index_fallback_reason: fallbackReason,
          evidence_anchors: [],
        },
      },
    },
  });
}

async function resolveDocling(input: OpenAIFactLedgerInput): Promise<DoclingOutput> {
  if (input.document ?? input.docling) return (input.document ?? input.docling)!;

  if ((input.rawText ?? "").trim().length > 0) {
    const paragraphs = (input.rawText ?? "").split(/\n\s*\n/).filter((p) => p.trim().length > 0);
    return {
      text_blocks: paragraphs.map((text, i) => ({ block_index: i, type: "paragraph", text: text.trim() })),
      tables: [],
      fields: [],
      full_text: input.rawText,
    };
  }

  if (input.fileBase64) {
    const binaryString = atob(input.fileBase64);
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) bytes[i] = binaryString.charCodeAt(i);
    return await parseDocument(bytes, input.fileName || "document", input.fileMimeType || "application/pdf");
  }

  return { text_blocks: [], tables: [], fields: [], full_text: "" };
}

export async function runOpenAIFactLedgerPipeline(
  input: OpenAIFactLedgerInput,
  options: OpenAIFactLedgerOptions = {},
): Promise<ExtractionPipelineResult> {
  const startTime = Date.now();
  let indexResolution: any = null;

  try {
    const doclingRaw = await resolveDocling(input);
    // Phase 6: opt-in canonical-layout-backed index (ENABLE_DOCUMENT_INTELLIGENCE_V3
    // only), falling straight back to the existing legacy_evidence_index path
    // (document-index.ts, untouched) on any failure. Default/flag-off
    // behavior is byte-for-byte what this line did before Phase 6.
    indexResolution = await resolveDocumentIndex(doclingRaw, { canonicalLayout: input.canonicalLayout ?? null });
    const docIndex = indexResolution.index;

    if (docIndex.fullText.trim().length < 10 && !input.fileBase64) {
      return fallbackResult(
        "Document text is too short for extraction",
        startTime,
        undefined,
        undefined,
        indexResolution?.indexSource,
        indexResolution?.fallbackReason,
      );
    }

    const profile = await classifyDocumentProfile({
      docIndex,
      documentSubtype: input.documentSubtype ?? null,
    });

    const extractorArgs = {
      docIndex,
      profile,
      moduleType: input.moduleType,
      fileBase64: input.fileBase64 ?? null,
      fileMimeType: input.fileMimeType ?? null,
      fileModeOverride: options.fileMode,
      deadlineAt: options.deadlineAt,
      provenance: options.provenance,
      maxChunks: options.maxChunks,
      resume: options.resume,
      onProgress: options.onProgress,
    };
    const factLedger = adaptiveExtractionDisabled()
      ? await extractFactLedger(extractorArgs)
      : await extractFactLedgerAdaptive(extractorArgs);

    // Phase 6 Task E: when the canonical layout index was actually used,
    // enrich each fact with block-level evidence (never fabricated -- a
    // fact whose page/source_text doesn't match a real block gets empty
    // blockIds/polygon, exactly as if no enrichment had run). Facts
    // themselves (category/value/sourceText/sourcePage/confidence) are
    // unchanged either way, so mapping/dedup behavior downstream is
    // identical regardless of which index resolved.
    const canonicalLayoutForEnrichment =
      indexResolution.indexSource === "canonical_layout" ? (docIndex as any).canonicalLayout ?? null : null;
    const enrichedFacts = canonicalLayoutForEnrichment
      ? factLedger.facts.map((fact) => enrichFactWithBlockEvidence(fact, canonicalLayoutForEnrichment))
      : factLedger.facts;

    const mapped = mapFactsToStandardFields({
      facts: enrichedFacts,
      moduleType: input.moduleType,
    });

    const currentFields = mapped.records[0]?.fields || {};
    const rescued = rescueNearMissedFacts({
      unmappedFacts: mapped.unmappedFacts,
      currentFields,
    });
    
    // Merge rescued fields into the record
    for (const [key, value] of Object.entries(rescued)) {
      currentFields[key] = value as any;
    }

    const dynamicItems = surfaceDynamicFacts({
      unmappedFacts: mapped.unmappedFacts,
      docIndex,
      documentProfile: profile.documentProfile,
      currentMappedFields: currentFields,
    });

    const approvalBlockers = computeProfileApprovalBlockers({
      profile: profile.documentProfile,
      standardFields: mapped.records[0] ?? null,
    });

    const flatRows = flattenRecords(mapped.records, input.moduleType);
    computeDerivedFields(flatRows, input.moduleType);

    const llmFieldsExtracted = Object.keys(mapped.records[0]?.fields || {}).length;
    const avgConfidence = flatRows.length > 0
      ? Math.round(flatRows.reduce((sum, r) => sum + ((r.confidence_score as number) || 0), 0) / flatRows.length)
      : 0;
    // "llm_only" only when facts actually mapped to standard fields — a
    // parsed-but-nothing-found row (e.g. OpenAI unreachable, all chunks
    // failed) must not falsely report a successful LLM run.
    const method: ExtractionPipelineResult["method"] =
      flatRows.length > 0 && llmFieldsExtracted > 0 ? "llm_only" : "fallback";
    const fieldSnapshot = snapshotFieldMap(mapped.records as any[]);
    const processingTimeMs = Date.now() - startTime;

    return withOpenAIFactLedgerDebug({
      rows: flatRows,
      method,
      warnings: factLedger.warnings,
      validationErrors: mapped.validationErrors,
      metadata: {
        ruleFieldsExtracted: 0,
        tableFieldsExtracted: 0,
        llmFieldsExtracted,
        totalRecords: flatRows.length,
        avgConfidence,
        chunksProcessed: factLedger.chunksProcessed,
        chunksTotal: factLedger.chunksTotal ?? factLedger.chunksProcessed,
        chunksSucceeded: factLedger.chunksSucceeded ?? factLedger.chunksProcessed,
        chunksFailed: factLedger.chunksFailed ?? 0,
        chunksTruncated: factLedger.chunksTruncated ?? false,
        partialResult: factLedger.partialResult ?? false,
        peakConcurrency: factLedger.peakConcurrency ?? null,
        processingTimeMs,
        parsingMethod: doclingRaw.extraction_method || "text",
        charCount: docIndex.fullText.length,
        extractionDebug: {
          // Must match the SHARED constant (contract-version.ts /
          // leaseReviewSchema.js's CURRENT_EXTRACTION_CONTRACT_VERSION) that
          // every extraction path is supposed to stamp -- this was
          // previously a provider-specific literal ("openai-fact-ledger-v1")
          // that never matched, so LeaseReview.jsx's staleness check always
          // failed for every openai_fact_ledger extraction (the default,
          // primary provider) regardless of how fresh it actually was.
          extraction_contract_version: EXTRACTION_CONTRACT_VERSION,
          // Same shape/keys legacy_hybrid's pipeline.ts populates, so any
          // downstream consumer that reads these off metadata.extractionDebug
          // works unchanged regardless of provider.
          merged_field_sources: fieldSnapshot,
          validated_field_values: fieldSnapshot,
          openai_fact_ledger: {
            document_profile: profile.documentProfile,
            document_profile_confidence: profile.confidence,
            document_profile_method: profile.method,
            facts_extracted_count: factLedger.facts.length,
            chunks_processed_count: factLedger.chunksProcessed,
            chunks_total_count: factLedger.chunksTotal ?? factLedger.chunksProcessed,
            chunks_succeeded_count: factLedger.chunksSucceeded ?? factLedger.chunksProcessed,
            chunks_failed_count: factLedger.chunksFailed ?? 0,
            chunks_truncated: factLedger.chunksTruncated ?? false,
            failed_chunk_indexes: factLedger.failedChunkIndexes ?? [],
            partial_result: factLedger.partialResult ?? false,
            peak_concurrency: factLedger.peakConcurrency ?? null,
            continuation_required: factLedger.continuationRequired ?? false,
            continuation_reason: factLedger.continuationReason ?? null,
            next_chunk_index: factLedger.nextChunkIndex ?? null,
            resumed_from_chunk_index: factLedger.resumedFromChunkIndex ?? null,
            facts_mapped_count: llmFieldsExtracted,
            facts_unmapped_count: mapped.unmappedFacts.length,
            approval_blockers: approvalBlockers.blockers,
            dynamic_items: dynamicItems,
            // Release 1 candidate-decision audit trail: facts the domain-aware
            // mapper rejected for a field their own labels/keywords would
            // otherwise have matched (e.g. a late-fee clause that would have
            // scored against admin_fee_pct on keyword length alone). No DB
            // table yet — visible here for debugging/tuning; forward-
            // compatible with document_validation_drops (Release 2).
            rejected_candidates: mapped.rejectedCandidates,
            // Micro-step 0 (pipeline-audit provenance, additive/optional —
            // see openai-fact-ledger/types.ts's FieldSelectionProvenance and
            // LEASE_EXTRACTION_UI_PIPELINE_AUDIT.md Section 16.3). Bounded to
            // TRACKED_PROVENANCE_FIELDS in fact-field-mapper.ts, not all
            // fields. `?? {}` so an older mapper build (or a test fixture
            // built before this change) that doesn't return fieldProvenance
            // at all degrades to an empty object here, never undefined.
            field_provenance: mapped.fieldProvenance ?? {},
            // Section-Aware Candidate Router instrumentation (adaptive-
            // extractor.ts) -- per-domain call/skip decisions, escalation
            // reasons, token estimates, cache hits. `null` when
            // DISABLE_ADAPTIVE_FACT_LEDGER_EXTRACTION forced the legacy
            // whole-document chunking path instead.
            adaptive_extraction: (factLedger as any).adaptiveInstrumentation ?? null,
            // Phase 6 Task G: diagnostic-only, not read by any business logic.
            document_index_source: indexResolution.indexSource,
            document_index_fallback_reason: indexResolution.fallbackReason,
            // Azure+OpenAI Phase 4E: structured failure signal, only present
            // when the chunk-aggregation in fact-ledger-extractor.ts decided
            // the document produced nothing usable overall (never set merely
            // because some individual chunks failed while others succeeded).
            ...(factLedger.failureClassification
              ? {
                failure_classification: factLedger.failureClassification,
                failure_http_status: factLedger.failureHttpStatus ?? null,
                // Provider's own error code (e.g. Azure's "DeploymentNotFound"),
                // the exact request URL (no secrets — the key travels only in
                // headers), and the provider's request ID for this failure.
                // None of these are secrets; all are safe to persist/query.
                failure_provider_error_code: factLedger.failureProviderErrorCode ?? null,
                failure_request_id: factLedger.failureRequestId ?? null,
                failure_request_url: factLedger.failureRequestUrl ?? null,
              }
              : {}),
            // Phase 6 Task E: available whenever the canonical layout index
            // ran, so a future phase can persist block-level evidence into
            // document_claim_evidence without re-deriving it. Empty array
            // (not populated at all) when the legacy index was used, or when
            // enrichment found no block match for a given fact.
            evidence_anchors: canonicalLayoutForEnrichment
              ? enrichedFacts.map((fact) => ({
                category: fact.category,
                source_text: fact.sourceText,
                source_page: fact.sourcePage,
                block_ids: fact.blockIds,
                polygon: fact.polygon,
                support_type: fact.supportType,
              }))
              : [],
          },
        },
      },
    });
  } catch (error) {
    const classification = error instanceof LLMProviderError ? error.classification : undefined;
    const httpStatus = error instanceof LLMProviderError ? error.httpStatus : undefined;
    const providerErrorCode = error instanceof LLMProviderError ? error.providerErrorCode : undefined;
    const requestId = error instanceof LLMProviderError ? error.requestId : undefined;
    const requestUrl = error instanceof LLMProviderError ? error.requestUrl : undefined;
    return fallbackResult(
      `OpenAI fact ledger pipeline failed: ${(error as Error)?.message ?? error}`,
      startTime,
      classification,
      httpStatus,
      indexResolution?.indexSource,
      indexResolution?.fallbackReason,
      providerErrorCode,
      requestId,
      requestUrl,
    );
  }
}

export { runOpenAIFactLedgerPipeline as runVertexFactLedgerPipeline };
