// @ts-nocheck
export const FINANCIAL_RUNTIME_ERROR_CODES = {
  FINANCIAL_MODE_REQUIRES_CLAIMS_LEDGER: "FINANCIAL_MODE_REQUIRES_CLAIMS_LEDGER",
  FINANCIAL_ACTIVE_REQUIRES_CLAIMS_ACTIVE: "FINANCIAL_ACTIVE_REQUIRES_CLAIMS_ACTIVE",
  FINANCIAL_ACTIVE_REQUIRES_PACKAGE_ACTIVE: "FINANCIAL_ACTIVE_REQUIRES_PACKAGE_ACTIVE",
  FINANCIAL_MODE_CONFIGURATION_INVALID: "FINANCIAL_MODE_CONFIGURATION_INVALID",
  FINANCIAL_ACTIVE_GENERATION_MISMATCH: "FINANCIAL_ACTIVE_GENERATION_MISMATCH",
  FINANCIAL_EXTRACTION_RUN_MISMATCH: "FINANCIAL_EXTRACTION_RUN_MISMATCH",
  FINANCIAL_CALCULATION_MISSING: "FINANCIAL_CALCULATION_MISSING",
  FINANCIAL_CALCULATION_FAILED: "FINANCIAL_CALCULATION_FAILED",
  FINANCIAL_CALCULATION_STALE_GENERATION: "FINANCIAL_CALCULATION_STALE_GENERATION",
  FINANCIAL_PROJECTION_MISSING: "FINANCIAL_PROJECTION_MISSING",
  FINANCIAL_PROJECTION_FAILED: "FINANCIAL_PROJECTION_FAILED",
  FINANCIAL_PROJECTION_STALE_GENERATION: "FINANCIAL_PROJECTION_STALE_GENERATION",
  FINANCIAL_COMPATIBILITY_NOT_PERSISTED: "FINANCIAL_COMPATIBILITY_NOT_PERSISTED",
  FINANCIAL_CRITICAL_DATE_PROJECTION_INVALID: "FINANCIAL_CRITICAL_DATE_PROJECTION_INVALID",
  FINANCIAL_RUNTIME_FAILED: "FINANCIAL_RUNTIME_FAILED",
} as const;

export class FinancialRuntimeError extends Error {
  errorCode: string;

  constructor(errorCode: string, message = errorCode) {
    super(message);
    this.name = "FinancialRuntimeError";
    this.errorCode = errorCode;
  }
}