import {
  NOTIFICATION_MODULES,
  NOTIFICATION_SCOPES,
  NOTIFICATION_TYPES,
  ROLE_KEYS,
} from "@/lib/notifications/notificationConstants";

const role = (roleKey, notificationType, options = {}) => ({
  role: roleKey,
  notificationType,
  requiresAction: [
    NOTIFICATION_TYPES.ACTION_REQUIRED,
    NOTIFICATION_TYPES.APPROVAL_REQUIRED,
    NOTIFICATION_TYPES.CORRECTION_REQUIRED,
    NOTIFICATION_TYPES.CRITICAL,
  ].includes(notificationType),
  ...options,
});

const assigned = (notificationType, options = {}) => ({
  assigned: true,
  notificationType,
  requiresAction: true,
  ...options,
});

const finalOwnerApproval = (module) => ({
  finalOrgOwnerApproval: true,
  module,
});

const policies = {
  "critical_date.due_soon": {
    module: NOTIFICATION_MODULES.CRITICAL_DATES,
    entityType: "critical_date",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "critical_dates.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "critical_dates.manage" }),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.INFORMATIONAL, { external: true }),
      role(ROLE_KEYS.TENANT, NOTIFICATION_TYPES.INFORMATIONAL, { external: true, tenantConditional: true }),
      assigned(NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "critical_dates.manage" }),
    ],
  },
  "critical_date.due_today": {
    module: NOTIFICATION_MODULES.CRITICAL_DATES,
    entityType: "critical_date",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "critical_dates.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "critical_dates.manage" }),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.INFORMATIONAL, { external: true }),
      role(ROLE_KEYS.TENANT, NOTIFICATION_TYPES.INFORMATIONAL, { external: true, tenantConditional: true }),
      assigned(NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "critical_dates.manage" }),
    ],
  },
  "critical_date.overdue": {
    module: NOTIFICATION_MODULES.CRITICAL_DATES,
    entityType: "critical_date",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "critical_dates.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.CRITICAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.CRITICAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.CRITICAL, { permission: "critical_dates.manage" }),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.INFORMATIONAL, { external: true }),
      role(ROLE_KEYS.TENANT, NOTIFICATION_TYPES.INFORMATIONAL, { external: true, tenantConditional: true }),
      assigned(NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "critical_dates.manage" }),
    ],
  },
  "portfolio.created": {
    module: NOTIFICATION_MODULES.PORTFOLIO,
    entityType: "portfolio",
    scope: NOTIFICATION_SCOPES.PORTFOLIO,
    permission: "portfolio.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.INFORMATIONAL),
    ],
  },
  "portfolio.manager_assigned": {
    module: NOTIFICATION_MODULES.PORTFOLIO,
    entityType: "portfolio",
    scope: NOTIFICATION_SCOPES.PORTFOLIO,
    permission: "portfolio.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.ACTION_REQUIRED),
      assigned(NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "portfolio.manage" }),
    ],
  },
  "property.created": {
    module: NOTIFICATION_MODULES.PROPERTY,
    entityType: "property",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "property.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.INFORMATIONAL, { external: true }),
    ],
  },
  "property.manager_assigned": {
    module: NOTIFICATION_MODULES.PROPERTY,
    entityType: "property",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "property.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.ACTION_REQUIRED),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.INFORMATIONAL, { external: true }),
      assigned(NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "property.manage" }),
    ],
  },
  "property.bulk_import_completed": {
    module: NOTIFICATION_MODULES.PROPERTY,
    entityType: "property",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "property.view",
    recipients: [
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.INFORMATIONAL),
      assigned(NOTIFICATION_TYPES.INFORMATIONAL, { permission: "property.view" }),
    ],
  },
  "property.bulk_import_failed": {
    module: NOTIFICATION_MODULES.PROPERTY,
    entityType: "property",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "property.view",
    recipients: [
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.INFORMATIONAL),
      assigned(NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "property.manage" }),
    ],
  },
  "lease.uploaded": {
    module: NOTIFICATION_MODULES.LEASE,
    entityType: "lease",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "lease.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.INFORMATIONAL),
      assigned(NOTIFICATION_TYPES.INFORMATIONAL, { permission: "lease.view" }),
    ],
  },
  "lease.extraction_completed": {
    module: NOTIFICATION_MODULES.LEASE,
    entityType: "lease",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "lease.view",
    recipients: [
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.AUDITOR, NOTIFICATION_TYPES.INFORMATIONAL),
      assigned(NOTIFICATION_TYPES.INFORMATIONAL, { permission: "lease.view" }),
    ],
  },
  "lease.review_required": {
    module: NOTIFICATION_MODULES.LEASE,
    entityType: "lease",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "lease.review",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "lease.review" }),
      role(ROLE_KEYS.AUDITOR, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "lease.review" }),
      assigned(NOTIFICATION_TYPES.INFORMATIONAL, { permission: "lease.view" }),
    ],
  },
  "lease.ready_for_approval": {
    module: NOTIFICATION_MODULES.LEASE,
    entityType: "lease",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "lease.approve",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "lease.approve" }),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.ACTION_REQUIRED, { external: true, permission: "lease.approve" }),
      role(ROLE_KEYS.AUDITOR, NOTIFICATION_TYPES.INFORMATIONAL),
    ],
  },
  "lease.pm_approved": {
    module: NOTIFICATION_MODULES.LEASE,
    entityType: "lease",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "lease.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.ACTION_REQUIRED, { external: true }),
    ],
  },
  "lease.asset_owner_approval_required": {
    module: NOTIFICATION_MODULES.LEASE,
    entityType: "lease",
    scope: NOTIFICATION_SCOPES.ASSET,
    permission: "lease.approve",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.ACTION_REQUIRED, { external: true }),
    ],
  },
  "lease.org_owner_approval_required": {
    module: NOTIFICATION_MODULES.LEASE,
    entityType: "lease",
    scope: NOTIFICATION_SCOPES.ORGANIZATION,
    permission: "lease.approve",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.APPROVAL_REQUIRED, { permission: "lease.approve" }),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.INFORMATIONAL, { external: true }),
    ],
  },
  "lease.approved": {
    module: NOTIFICATION_MODULES.LEASE,
    entityType: "lease",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "lease.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.APPROVED, { external: true }),
      role(ROLE_KEYS.AUDITOR, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.TENANT, NOTIFICATION_TYPES.INFORMATIONAL, { external: true, tenantConditional: true }),
      assigned(NOTIFICATION_TYPES.INFORMATIONAL, { permission: "lease.view" }),
    ],
  },
  "lease.rejected": {
    module: NOTIFICATION_MODULES.LEASE,
    entityType: "lease",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "lease.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.REJECTED),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.REJECTED),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.REJECTED),
      role(ROLE_KEYS.AUDITOR, NOTIFICATION_TYPES.REJECTED),
      assigned(NOTIFICATION_TYPES.CORRECTION_REQUIRED, { permission: "lease.edit" }),
    ],
  },
  "lease.correction_required": {
    module: NOTIFICATION_MODULES.LEASE,
    entityType: "lease",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "lease.edit",
    recipients: [
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.CORRECTION_REQUIRED, { permission: "lease.edit" }),
      role(ROLE_KEYS.AUDITOR, NOTIFICATION_TYPES.INFORMATIONAL),
      assigned(NOTIFICATION_TYPES.CORRECTION_REQUIRED, { permission: "lease.edit" }),
    ],
  },
  "expense.submitted": {
    module: NOTIFICATION_MODULES.EXPENSE,
    entityType: "expense",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "expense.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "expense.review" }),
      role(ROLE_KEYS.FINANCE, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "expense.review" }),
      role(ROLE_KEYS.ACCOUNTING, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "expense.review" }),
    ],
  },
  "expense.review_required": {
    module: NOTIFICATION_MODULES.EXPENSE,
    entityType: "expense",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "expense.review",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "expense.review" }),
      role(ROLE_KEYS.FINANCE, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "expense.review" }),
      role(ROLE_KEYS.ACCOUNTING, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "expense.review" }),
      role(ROLE_KEYS.AUDITOR, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "expense.review", when: "audit_required" }),
    ],
  },
  "expense.final_approval_required": {
    ...finalOwnerApproval(NOTIFICATION_MODULES.EXPENSE),
    entityType: "expense",
    scope: NOTIFICATION_SCOPES.ORGANIZATION,
    permission: "expense.approve",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.APPROVAL_REQUIRED, { permission: "expense.approve" }),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.INFORMATIONAL, { external: true }),
      role(ROLE_KEYS.FINANCE, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ACCOUNTING, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.AUDITOR, NOTIFICATION_TYPES.INFORMATIONAL),
    ],
  },
  "expense.approved": {
    module: NOTIFICATION_MODULES.EXPENSE,
    entityType: "expense",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "expense.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.INFORMATIONAL, { external: true }),
      role(ROLE_KEYS.FINANCE, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.ACCOUNTING, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.AUDITOR, NOTIFICATION_TYPES.APPROVED),
    ],
  },
  "expense.rejected": {
    module: NOTIFICATION_MODULES.EXPENSE,
    entityType: "expense",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "expense.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.REJECTED),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.REJECTED),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.REJECTED),
      role(ROLE_KEYS.FINANCE, NOTIFICATION_TYPES.REJECTED),
      role(ROLE_KEYS.ACCOUNTING, NOTIFICATION_TYPES.REJECTED),
      role(ROLE_KEYS.AUDITOR, NOTIFICATION_TYPES.REJECTED),
      assigned(NOTIFICATION_TYPES.CORRECTION_REQUIRED, { permission: "expense.edit" }),
    ],
  },
  "cam.eligible": {
    module: NOTIFICATION_MODULES.CAM,
    entityType: "expense",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "cam.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.INFORMATIONAL, { external: true }),
      role(ROLE_KEYS.FINANCE, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "cam.review" }),
      role(ROLE_KEYS.ACCOUNTING, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "cam.review" }),
    ],
  },
  "cam.calculation_generated": {
    module: NOTIFICATION_MODULES.CAM,
    entityType: "cam",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "cam.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.INFORMATIONAL, { external: true }),
      role(ROLE_KEYS.FINANCE, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "cam.review" }),
      role(ROLE_KEYS.ACCOUNTING, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "cam.review" }),
    ],
  },
  "cam.review_required": {
    module: NOTIFICATION_MODULES.CAM,
    entityType: "cam",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "cam.review",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "cam.review" }),
      role(ROLE_KEYS.FINANCE, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "cam.review" }),
      role(ROLE_KEYS.ACCOUNTING, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "cam.review" }),
      role(ROLE_KEYS.AUDITOR, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "cam.review" }),
    ],
  },
  "cam.final_approval_required": {
    ...finalOwnerApproval(NOTIFICATION_MODULES.CAM),
    entityType: "cam",
    scope: NOTIFICATION_SCOPES.ORGANIZATION,
    permission: "cam.approve",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.APPROVAL_REQUIRED, { permission: "cam.approve" }),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.INFORMATIONAL, { external: true }),
      role(ROLE_KEYS.FINANCE, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ACCOUNTING, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.AUDITOR, NOTIFICATION_TYPES.INFORMATIONAL),
    ],
  },
  "cam.approved": {
    module: NOTIFICATION_MODULES.CAM,
    entityType: "cam",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "cam.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.INFORMATIONAL, { external: true }),
      role(ROLE_KEYS.FINANCE, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.ACCOUNTING, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.AUDITOR, NOTIFICATION_TYPES.APPROVED),
    ],
  },
  "cam.reconciliation_ready": {
    module: NOTIFICATION_MODULES.CAM,
    entityType: "cam_reconciliation",
    scope: NOTIFICATION_SCOPES.TENANT,
    permission: "cam.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.INFORMATIONAL, { external: true }),
      role(ROLE_KEYS.FINANCE, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ACCOUNTING, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.TENANT, NOTIFICATION_TYPES.ACTION_REQUIRED, { external: true, tenantPublishedOnly: true }),
    ],
  },
  "budget.generated": {
    module: NOTIFICATION_MODULES.BUDGET,
    entityType: "budget",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "budget.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.INFORMATIONAL, { external: true }),
      role(ROLE_KEYS.FINANCE, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ACCOUNTING, NOTIFICATION_TYPES.INFORMATIONAL),
    ],
  },
  "budget.review_required": {
    module: NOTIFICATION_MODULES.BUDGET,
    entityType: "budget",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "budget.review",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "budget.review" }),
      role(ROLE_KEYS.FINANCE, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "budget.review" }),
      role(ROLE_KEYS.ACCOUNTING, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "budget.review" }),
      role(ROLE_KEYS.AUDITOR, NOTIFICATION_TYPES.ACTION_REQUIRED, { permission: "budget.review", when: "audit_required" }),
    ],
  },
  "budget.final_approval_required": {
    ...finalOwnerApproval(NOTIFICATION_MODULES.BUDGET),
    entityType: "budget",
    scope: NOTIFICATION_SCOPES.ORGANIZATION,
    permission: "budget.approve",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.APPROVAL_REQUIRED, { permission: "budget.approve" }),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.INFORMATIONAL, { external: true }),
      role(ROLE_KEYS.FINANCE, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.ACCOUNTING, NOTIFICATION_TYPES.INFORMATIONAL),
      role(ROLE_KEYS.AUDITOR, NOTIFICATION_TYPES.INFORMATIONAL),
    ],
  },
  "budget.approved": {
    module: NOTIFICATION_MODULES.BUDGET,
    entityType: "budget",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "budget.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.ASSET_OWNER, NOTIFICATION_TYPES.INFORMATIONAL, { external: true }),
      role(ROLE_KEYS.FINANCE, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.ACCOUNTING, NOTIFICATION_TYPES.APPROVED),
      role(ROLE_KEYS.AUDITOR, NOTIFICATION_TYPES.APPROVED),
    ],
  },
  "budget.rejected": {
    module: NOTIFICATION_MODULES.BUDGET,
    entityType: "budget",
    scope: NOTIFICATION_SCOPES.PROPERTY,
    permission: "budget.view",
    recipients: [
      role(ROLE_KEYS.ORG_OWNER, NOTIFICATION_TYPES.REJECTED),
      role(ROLE_KEYS.ORG_ADMIN, NOTIFICATION_TYPES.REJECTED),
      role(ROLE_KEYS.PROPERTY_MANAGER, NOTIFICATION_TYPES.CORRECTION_REQUIRED, { permission: "budget.edit" }),
      role(ROLE_KEYS.FINANCE, NOTIFICATION_TYPES.CORRECTION_REQUIRED, { permission: "budget.edit" }),
      role(ROLE_KEYS.ACCOUNTING, NOTIFICATION_TYPES.CORRECTION_REQUIRED, { permission: "budget.edit" }),
      assigned(NOTIFICATION_TYPES.CORRECTION_REQUIRED, { permission: "budget.edit" }),
    ],
  },
};

export const NOTIFICATION_EVENT_POLICIES = Object.freeze(policies);

export const NOTIFICATION_EVENT_PERMISSIONS = Object.freeze(
  Object.fromEntries(
    Object.entries(policies).map(([eventType, policy]) => [
      eventType,
      {
        module: policy.module,
        permission: policy.permission,
        notificationType: policy.recipients?.[0]?.notificationType || NOTIFICATION_TYPES.INFORMATIONAL,
        finalOrgOwnerApproval: Boolean(policy.finalOrgOwnerApproval),
      },
    ])
  )
);

export function getNotificationPolicy(eventType) {
  return NOTIFICATION_EVENT_POLICIES[eventType] || null;
}

