// @ts-nocheck
import {
  LEASE_FINANCIAL_CHARGE_REGISTRY_HASH,
  LEASE_FINANCIAL_CHARGE_REGISTRY_VERSION,
} from "./financial-charge-registry-version.ts";

export const FINANCIAL_CHARGE_REGISTRY = [
  { chargeType: "additional_rent", displayName: "Additional Rent", chargeDomain: "additional_charge", financialRole: "tenant_payable", permittedAmountRoles: ["stated_amount", "billed_amount", "estimated_amount", "unresolved_amount"], permittedFrequencies: ["monthly", "annually", "quarterly", "irregular", "unknown"], periodAllowed: true, formulaAllowed: true, amortizationAllowed: false, tenantPayable: true, landlordPayable: false, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "percentage_rent", displayName: "Percentage Rent", chargeDomain: "percentage_rent", financialRole: "tenant_payable", permittedAmountRoles: ["percentage_rate", "threshold_amount", "formula_input", "formula_output_placeholder", "unresolved_amount"], permittedFrequencies: ["percentage_rent_period", "annually", "monthly", "unknown"], periodAllowed: true, formulaAllowed: true, amortizationAllowed: false, tenantPayable: true, landlordPayable: false, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "recurring_charge", displayName: "Recurring Charge", chargeDomain: "additional_charge", financialRole: "tenant_payable", permittedAmountRoles: ["stated_amount", "billed_amount", "estimated_amount", "unresolved_amount"], permittedFrequencies: ["monthly", "annually", "quarterly", "weekly", "daily", "irregular", "unknown"], periodAllowed: true, formulaAllowed: true, amortizationAllowed: false, tenantPayable: true, landlordPayable: false, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "one_time_charge", displayName: "One-Time Charge", chargeDomain: "additional_charge", financialRole: "tenant_payable", permittedAmountRoles: ["stated_amount", "billed_amount", "unresolved_amount"], permittedFrequencies: ["one_time", "per_occurrence", "unknown"], periodAllowed: true, formulaAllowed: false, amortizationAllowed: false, tenantPayable: true, landlordPayable: false, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "cam_estimate", displayName: "CAM Estimate", chargeDomain: "additional_charge", financialRole: "tenant_payable", permittedAmountRoles: ["estimated_amount", "stated_rate", "unresolved_amount"], permittedFrequencies: ["monthly", "annually", "quarterly", "unknown"], periodAllowed: true, formulaAllowed: false, amortizationAllowed: false, tenantPayable: true, landlordPayable: false, representsEstimate: true, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "operating_expense_estimate", displayName: "Operating Expense Estimate", chargeDomain: "additional_charge", financialRole: "tenant_payable", permittedAmountRoles: ["estimated_amount", "stated_rate", "unresolved_amount"], permittedFrequencies: ["monthly", "annually", "quarterly", "unknown"], periodAllowed: true, formulaAllowed: false, amortizationAllowed: false, tenantPayable: true, landlordPayable: false, representsEstimate: true, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "tax_estimate", displayName: "Tax Estimate", chargeDomain: "additional_charge", financialRole: "tenant_payable", permittedAmountRoles: ["estimated_amount", "stated_rate", "unresolved_amount"], permittedFrequencies: ["monthly", "annually", "quarterly", "unknown"], periodAllowed: true, formulaAllowed: false, amortizationAllowed: false, tenantPayable: true, landlordPayable: false, representsEstimate: true, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "insurance_estimate", displayName: "Insurance Estimate", chargeDomain: "additional_charge", financialRole: "tenant_payable", permittedAmountRoles: ["estimated_amount", "stated_rate", "unresolved_amount"], permittedFrequencies: ["monthly", "annually", "quarterly", "unknown"], periodAllowed: true, formulaAllowed: false, amortizationAllowed: false, tenantPayable: true, landlordPayable: false, representsEstimate: true, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "utility_charge", displayName: "Utility Charge", chargeDomain: "additional_charge", financialRole: "tenant_payable", permittedAmountRoles: ["stated_amount", "billed_amount", "estimated_amount", "unresolved_amount"], permittedFrequencies: ["monthly", "annually", "per_occurrence", "unknown"], periodAllowed: true, formulaAllowed: true, amortizationAllowed: false, tenantPayable: true, landlordPayable: false, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "management_fee", displayName: "Management Fee", chargeDomain: "additional_charge", financialRole: "tenant_payable", permittedAmountRoles: ["stated_amount", "estimated_amount", "percentage_rate", "unresolved_amount"], permittedFrequencies: ["monthly", "annually", "unknown"], periodAllowed: true, formulaAllowed: true, amortizationAllowed: false, tenantPayable: true, landlordPayable: false, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "administrative_fee", displayName: "Administrative Fee", chargeDomain: "additional_charge", financialRole: "tenant_payable", permittedAmountRoles: ["stated_amount", "estimated_amount", "percentage_rate", "unresolved_amount"], permittedFrequencies: ["monthly", "annually", "one_time", "unknown"], periodAllowed: true, formulaAllowed: true, amortizationAllowed: false, tenantPayable: true, landlordPayable: false, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "security_deposit", displayName: "Security Deposit", chargeDomain: "deposit_or_prepayment", financialRole: "escrow_or_deposit", permittedAmountRoles: ["deposit_amount", "unresolved_amount"], permittedFrequencies: ["one_time", "unknown"], periodAllowed: false, formulaAllowed: false, amortizationAllowed: false, tenantPayable: true, landlordPayable: false, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "prepaid_rent", displayName: "Prepaid Rent", chargeDomain: "deposit_or_prepayment", financialRole: "escrow_or_deposit", permittedAmountRoles: ["prepaid_amount", "deposit_amount", "unresolved_amount"], permittedFrequencies: ["one_time", "unknown"], periodAllowed: false, formulaAllowed: false, amortizationAllowed: false, tenantPayable: true, landlordPayable: false, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "deposit_component", displayName: "Deposit Component", chargeDomain: "deposit_or_prepayment", financialRole: "escrow_or_deposit", permittedAmountRoles: ["deposit_amount", "prepaid_amount", "unresolved_amount"], permittedFrequencies: ["one_time", "unknown"], periodAllowed: false, formulaAllowed: false, amortizationAllowed: false, tenantPayable: true, landlordPayable: false, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "tenant_improvement_allowance", displayName: "Tenant Improvement Allowance", chargeDomain: "allowance_or_contribution", financialRole: "landlord_payable", permittedAmountRoles: ["allowance_amount", "unresolved_amount"], permittedFrequencies: ["one_time", "unknown"], periodAllowed: true, formulaAllowed: false, amortizationAllowed: false, tenantPayable: false, landlordPayable: true, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "landlord_contribution", displayName: "Landlord Contribution", chargeDomain: "allowance_or_contribution", financialRole: "landlord_payable", permittedAmountRoles: ["contribution_amount", "allowance_amount", "unresolved_amount"], permittedFrequencies: ["one_time", "unknown"], periodAllowed: true, formulaAllowed: false, amortizationAllowed: false, tenantPayable: false, landlordPayable: true, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "reimbursement", displayName: "Reimbursement", chargeDomain: "reimbursement", financialRole: "landlord_payable", permittedAmountRoles: ["reimbursement_amount", "unresolved_amount"], permittedFrequencies: ["one_time", "per_occurrence", "unknown"], periodAllowed: true, formulaAllowed: true, amortizationAllowed: false, tenantPayable: false, landlordPayable: true, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "amortized_improvement_charge", displayName: "Amortized Improvement Charge", chargeDomain: "amortization_instruction", financialRole: "tenant_payable", permittedAmountRoles: ["principal_amount", "payment_amount", "stated_rate", "unresolved_amount"], permittedFrequencies: ["monthly", "amortization_period", "unknown"], periodAllowed: true, formulaAllowed: false, amortizationAllowed: true, tenantPayable: true, landlordPayable: false, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "equipment_charge", displayName: "Equipment Charge", chargeDomain: "additional_charge", financialRole: "tenant_payable", permittedAmountRoles: ["stated_amount", "billed_amount", "principal_amount", "payment_amount", "unresolved_amount"], permittedFrequencies: ["monthly", "one_time", "amortization_period", "unknown"], periodAllowed: true, formulaAllowed: false, amortizationAllowed: true, tenantPayable: true, landlordPayable: false, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "late_fee", displayName: "Late Fee", chargeDomain: "additional_charge", financialRole: "tenant_payable", permittedAmountRoles: ["stated_amount", "percentage_rate", "formula_input", "unresolved_amount"], permittedFrequencies: ["per_occurrence", "unknown"], periodAllowed: false, formulaAllowed: true, amortizationAllowed: false, tenantPayable: true, landlordPayable: false, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "holdover_charge", displayName: "Holdover Charge", chargeDomain: "additional_charge", financialRole: "tenant_payable", permittedAmountRoles: ["stated_amount", "percentage_rate", "formula_input", "unresolved_amount"], permittedFrequencies: ["monthly", "daily", "unknown"], periodAllowed: true, formulaAllowed: true, amortizationAllowed: false, tenantPayable: true, landlordPayable: false, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "credit", displayName: "Credit", chargeDomain: "credit_or_offset", financialRole: "credit_to_tenant", permittedAmountRoles: ["credit_amount", "unresolved_amount"], permittedFrequencies: ["one_time", "per_occurrence", "unknown"], periodAllowed: true, formulaAllowed: false, amortizationAllowed: false, tenantPayable: false, landlordPayable: true, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
  { chargeType: "unresolved_charge", displayName: "Unresolved Charge", chargeDomain: "unresolved", financialRole: "unresolved", permittedAmountRoles: ["unresolved_amount"], permittedFrequencies: ["unknown"], periodAllowed: true, formulaAllowed: true, amortizationAllowed: true, tenantPayable: false, landlordPayable: false, representsEstimate: false, belongsToBaseRentSchedules: false, p5ProcessingRequired: true },
] as const;

export function getFinancialChargeRegistryEntry(chargeType: string) {
  return FINANCIAL_CHARGE_REGISTRY.find((entry) => entry.chargeType === chargeType) ?? null;
}

export function canonicalFinancialChargeRegistryPayload() {
  return FINANCIAL_CHARGE_REGISTRY.map((entry) => ({
    ...entry,
    registryVersion: LEASE_FINANCIAL_CHARGE_REGISTRY_VERSION,
  })).sort((a, b) => a.chargeType.localeCompare(b.chargeType));
}

export async function computeFinancialChargeRegistryHash(): Promise<string> {
  const bytes = new TextEncoder().encode(JSON.stringify(canonicalFinancialChargeRegistryPayload()));
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join("");
}

export function assertFinancialChargeRegistryHashConfigured() {
  return LEASE_FINANCIAL_CHARGE_REGISTRY_HASH !== "PENDING";
}
