// Generates HANDOFF_ISSUES.xlsx — all challenges, bugs, issues, fixes, and replacements
// from the CRE Financial Suite handoff audit. Fix recommendations are framed from
// an OPEN-SOURCE + UNLIMITED-TOKENS perspective (no SaaS dependencies, no token budgets).
//
// Usage: node scripts/generate_handoff_excel.mjs

import XLSX from 'xlsx';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_PATH = path.resolve(__dirname, '..', 'HANDOFF_ISSUES.xlsx');

// Column order shared across every sheet so the workbook reads consistently
const COLUMNS = [
  'ID',
  'Category',
  'Title',
  'Severity',
  'Area / Component',
  'Files / Location',
  'Root Cause',
  'Business Impact',
  'Current Approach',
  'Replace With (Open Source)',
  'Unlimited-Token Strategy',
  'Rationale',
  'Priority',
  'Est. Effort',
];

// Helper so each row is written in the correct column order
const row = (o) => COLUMNS.map((c) => o[c] ?? '');

// ─────────────────────────────────────────────────────────────────────────────
// SHEET 1 — SUMMARY / LEGEND
// ─────────────────────────────────────────────────────────────────────────────
const summaryRows = [
  ['CRE Financial Suite — Issue Register & Open-Source Replacement Plan'],
  [`Generated: ${new Date().toISOString().slice(0, 10)}`],
  [],
  ['Severity codes'],
  ['C', 'Critical — fix immediately (security / data-loss / tenancy)'],
  ['H', 'High — fix in next 30 days'],
  ['M', 'Medium — fix in next 90 days'],
  ['L', 'Low — backlog / nice-to-have'],
  [],
  ['Sheet guide'],
  ['1. Summary', 'This sheet'],
  ['2. Architecture', 'Platform & pipeline-level issues'],
  ['3. Security', 'Auth, tenancy, secrets, CSP, rate limiting'],
  ['4. Performance & Scaling', 'Timeouts, DB perf, RLS perf, bundle size'],
  ['5. AI / Extraction / OCR', 'Gemini, Docling, parsers, prompts'],
  ['6. Frontend / UX', 'Routing, state, code splitting, a11y'],
  ['7. Backend / DB / Migrations', 'Schema drift, migrations, audit'],
  ['8. Auth / Access / Observability', 'RBAC holes, logging, compliance'],
  ['9. Replace / Redesign', 'Big-ticket swaps'],
  ['10. Open-Source Stack', 'Full replacement stack at a glance'],
  ['11. Priorities', 'Ordered roadmap'],
  [],
  ['Open-source + unlimited-tokens assumptions used in the "Replace With" column'],
  ['• Every SaaS dependency can be self-hosted; no vendor lock-in.'],
  ['• LLM inference is free and unmetered (vLLM / Ollama / llama.cpp on owned GPUs).'],
  ['• Large-context models (Qwen2.5-1M, Llama 4 10M ctx, DeepSeek V3) remove the need for chunking / snippet windows.'],
  ['• Chunking, confidence-threshold skipping, and "LLM only for missing fields" become optimisations, not necessities.'],
  ['• Multi-pass, ensemble, and self-critique extraction become feasible — use them for financial correctness.'],
];

// ─────────────────────────────────────────────────────────────────────────────
// SHEET 2 — ARCHITECTURE
// ─────────────────────────────────────────────────────────────────────────────
const architecture = [
  {
    ID: 'A1',
    Category: 'Architecture',
    Title: 'Edge functions chained via synchronous HTTP',
    Severity: 'H',
    'Area / Component': 'Document pipeline',
    'Files / Location': 'supabase/functions/ingest-file/index.ts',
    'Root Cause': 'ingest-file awaits parse-* → normalize → validate → store serially; every edge fn has 150s budget',
    'Business Impact': 'Large docs time out; retries restart the chain; no backpressure',
    'Current Approach': 'callEdgeFunction() with HTTP exponential backoff inside ingest-file',
    'Replace With (Open Source)': 'pg-boss (Postgres-native queue) OR River (Go queue on Postgres) OR Temporal (self-hosted) OR BullMQ on self-hosted Redis. Workers run as Deno processes or a small Node/Python fleet.',
    'Unlimited-Token Strategy': 'Each job can afford a full-document LLM pass with huge context; pipeline becomes: enqueue → worker reads file → single large-context extraction → write results. No intermediate state needed.',
    Rationale: 'Decouples HTTP timeouts from pipeline work; enables retry/DLQ/scheduling; Postgres-based queues keep the stack simple.',
    Priority: 'Immediate',
    'Est. Effort': '2–3 weeks',
  },
  {
    ID: 'A2',
    Category: 'Architecture',
    Title: 'Two parallel access-scope tables',
    Severity: 'H',
    'Area / Component': 'DB / RBAC',
    'Files / Location': 'migrations 20260408_enterprise_schema.sql (user_access) + 20260422000200_enterprise_access_control.sql (member_*)',
    'Root Cause': 'New normalized member_* tables added without migrating from user_access; both active',
    'Business Impact': 'Scope reads inconsistent; RLS helpers still use user_access; divergence risk',
    'Current Approach': 'Dual-write via service code (partial)',
    'Replace With (Open Source)': 'Consolidate to a single grants table (member_scope_access) with scope_type enum; migrate data; drop user_access. All within Postgres — no new tooling needed.',
    'Unlimited-Token Strategy': 'N/A — structural DB issue',
    Rationale: 'One source of truth for scope; simpler RLS; cleaner audit',
    Priority: 'High',
    'Est. Effort': '1 week',
  },
  {
    ID: 'A3',
    Category: 'Architecture',
    Title: 'Duplicate business engines (CAM, budget, lease, parsing)',
    Severity: 'H',
    'Area / Component': 'Business logic',
    'Files / Location': 'src/services/camEngine.js + supabase/functions/_shared/cam-calculator.ts (and others)',
    'Root Cause': 'Frontend "optimistic" engines developed in parallel with backend compute-*; now disagree',
    'Business Impact': 'Numbers on screen can differ from persisted calculations → financial correctness risk',
    'Current Approach': 'Two code paths, no shared tests',
    'Replace With (Open Source)': 'Extract the server TypeScript engines into a shared package (pnpm/yarn workspace) published internally; both Deno edge functions and the React app import the same code. No vendor needed — just a monorepo.',
    'Unlimited-Token Strategy': 'With an LLM agent reviewing PRs, auto-flag any change to one engine that does not update the other or a shared spec.',
    Rationale: 'One source of truth; unit-tested once; no drift',
    Priority: 'High',
    'Est. Effort': '2 weeks',
  },
  {
    ID: 'A4',
    Category: 'Architecture',
    Title: '@ts-nocheck on every edge function',
    Severity: 'M',
    'Area / Component': 'Type safety',
    'Files / Location': 'all supabase/functions/*/index.ts',
    'Root Cause': 'Deno strict typechecking never configured',
    'Business Impact': 'Silent type errors; data drops; slow onboarding',
    'Current Approach': '// @ts-nocheck at top of every file',
    'Replace With (Open Source)': 'deno check in CI via GitHub Actions / Gitea Actions / Drone CI (all OSS). Generate types from Supabase schema with the OSS supabase CLI (supabase gen types typescript).',
    'Unlimited-Token Strategy': 'Run an LLM to auto-migrate files one-by-one: it reads the function, infers types, submits a PR.',
    Rationale: 'Catches bugs at build time',
    Priority: 'Medium',
    'Est. Effort': '1 week',
  },
  {
    ID: 'A5',
    Category: 'Architecture',
    Title: 'No frontend/backend test suites',
    Severity: 'H',
    'Area / Component': 'QA',
    'Files / Location': 'repo root has ad-hoc test-*.cjs/js scripts',
    'Root Cause': 'No framework adopted',
    'Business Impact': 'Regressions ship; every CAM/budget change is terrifying',
    'Current Approach': 'Manual smoke testing',
    'Replace With (Open Source)': 'Vitest (frontend) + Deno.test (edge functions) + Playwright (e2e) + Testcontainers for ephemeral Postgres. All OSS; runs in any CI.',
    'Unlimited-Token Strategy': 'Use an LLM to generate test cases for CAM/budget math from property configs; thousands of fuzzed scenarios essentially free.',
    Rationale: 'Core financial correctness needs tests',
    Priority: 'High',
    'Est. Effort': '2 weeks to bootstrap',
  },
  {
    ID: 'A6',
    Category: 'Architecture',
    Title: 'No monorepo / package boundaries',
    Severity: 'M',
    'Area / Component': 'Code organisation',
    'Files / Location': 'repo root',
    'Root Cause': 'Frontend and edge functions share nothing except ad-hoc duplication',
    'Business Impact': 'Business logic drift; refactor pain',
    'Current Approach': 'Two trees (src/, supabase/functions/)',
    'Replace With (Open Source)': 'pnpm workspaces OR Nx OR Turborepo (all OSS). Packages: @cre/engines, @cre/schemas, @cre/extractors, @cre/types.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Enables shared code without copy-paste',
    Priority: 'Medium',
    'Est. Effort': '1 week',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SHEET 3 — SECURITY
// ─────────────────────────────────────────────────────────────────────────────
const security = [
  {
    ID: 'S1',
    Category: 'Security',
    Title: 'Self-insert org_admin membership policy is too permissive',
    Severity: 'C',
    'Area / Component': 'Auth / RLS',
    'Files / Location': 'supabase/schema.sql:187-202',
    'Root Cause': 'Policy lets any authenticated user insert their OWN membership as org_admin if they have none in that org',
    'Business Impact': 'If an attacker learns any org_id, they can attach themselves as org_admin and see/modify that tenant\'s data',
    'Current Approach': 'WITH CHECK user_id = auth.uid() AND role = org_admin AND NOT EXISTS (...)',
    'Replace With (Open Source)': 'Replace policy with a SECURITY DEFINER plpgsql function register_owner_membership(org_id uuid) that only succeeds when called from the first-login edge fn (guarded by a one-time token stored in profiles).',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Removes the public self-insert surface',
    Priority: 'Immediate',
    'Est. Effort': '1 day',
  },
  {
    ID: 'S2',
    Category: 'Security',
    Title: 'Super-admin getUserOrgId fallback picks "first org"',
    Severity: 'C',
    'Area / Component': 'Tenancy',
    'Files / Location': 'supabase/functions/_shared/supabase.ts:60-85',
    'Root Cause': 'For super admins without a real membership org_id, the code selects the first organisation in the system',
    'Business Impact': 'Compute / store / export edge functions silently operate against an arbitrary tenant\'s data',
    'Current Approach': 'SELECT id FROM organizations ORDER BY created_at LIMIT 1',
    'Replace With (Open Source)': 'Require an explicit org_id request param for super admins; return 400 otherwise. Add x-acting-org-id header pattern enforced in verifyUser.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Tenancy safety',
    Priority: 'Immediate',
    'Est. Effort': '2 days',
  },
  {
    ID: 'S3',
    Category: 'Security',
    Title: 'Super-admin create-fallback writes to random org',
    Severity: 'H',
    'Area / Component': 'Data integrity',
    'Files / Location': 'src/services/api.js:802-821',
    'Root Cause': 'When super admin creates data with no active org, resolveWritableOrgId() picks any org',
    'Business Impact': 'Cross-tenant data contamination from the admin UI',
    'Current Approach': 'Automatic fallback + console.warn',
    'Replace With (Open Source)': 'Force an explicit organisation picker for super admins (UI component). If org is not set, throw — do not auto-assign.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Data integrity',
    Priority: 'Immediate',
    'Est. Effort': '1 day',
  },
  {
    ID: 'S4',
    Category: 'Security',
    Title: 'assertCanWritePage uses window.location.pathname',
    Severity: 'M',
    'Area / Component': 'Auth',
    'Files / Location': 'src/lib/userPermissions.js:227-233',
    'Root Cause': 'Derives page name from the current URL; writes from modals or other pages bypass the check',
    'Business Impact': 'Permission bypasses that look fine on the surface',
    'Current Approach': 'const [segment] = pathname.split(\'/\')',
    'Replace With (Open Source)': 'Pass pageName explicitly from every caller (linted via ESLint rule). No new dep — just a refactor.',
    'Unlimited-Token Strategy': 'LLM-assisted codemod to rewrite all call sites in one sweep.',
    Rationale: 'Accurate permission enforcement',
    Priority: 'High',
    'Est. Effort': '1 week',
  },
  {
    ID: 'S5',
    Category: 'Security',
    Title: 'No rate limiting on public endpoints',
    Severity: 'H',
    'Area / Component': 'API surface',
    'Files / Location': 'submit-contact, signup, access_requests, invite-user',
    'Root Cause': 'No throttling layer in front of edge functions',
    'Business Impact': 'Spam; account enumeration; credential stuffing',
    'Current Approach': 'None',
    'Replace With (Open Source)': 'Caddy with rate-limit module OR Traefik middleware OR Kong Gateway (OSS) fronting Supabase. Per-IP + per-email buckets stored in Redis/Valkey.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Basic abuse protection',
    Priority: 'High',
    'Est. Effort': '3 days',
  },
  {
    ID: 'S6',
    Category: 'Security',
    Title: 'Service role key used in every edge function',
    Severity: 'M',
    'Area / Component': 'Blast radius',
    'Files / Location': '_shared/supabase.ts createAdminClient',
    'Root Cause': 'Edge functions need to bypass RLS for some ops; shortcut is to use service role everywhere',
    'Business Impact': 'One vulnerable function compromises the whole DB',
    'Current Approach': 'One key, full permissions',
    'Replace With (Open Source)': 'Create multiple Postgres roles (roles_writer, pipeline_worker, exporter) with least privilege; each edge fn loads its own role\'s JWT. Supabase supports this natively via custom GoTrue roles.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Defence in depth',
    Priority: 'Medium',
    'Est. Effort': '2 weeks',
  },
  {
    ID: 'S7',
    Category: 'Security',
    Title: 'No CSP / security headers in vercel.json',
    Severity: 'M',
    'Area / Component': 'Web',
    'Files / Location': 'vercel.json',
    'Root Cause': 'Headers never configured',
    'Business Impact': 'XSS blast radius; clickjacking; MIME sniffing',
    'Current Approach': 'Default Vercel headers only',
    'Replace With (Open Source)': 'Self-host frontend on Caddy (OSS) or Nginx with strict CSP, HSTS, X-Frame-Options, X-Content-Type-Options, Referrer-Policy, Permissions-Policy. Drop Vercel.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Web security baseline',
    Priority: 'Medium',
    'Est. Effort': '1 week',
  },
  {
    ID: 'S8',
    Category: 'Security',
    Title: 'Email HTML built via string concatenation (injection risk)',
    Severity: 'L',
    'Area / Component': 'Email templates',
    'Files / Location': 'signup/index.ts, invite-user/index.ts, send-email/index.ts',
    'Root Cause': 'No HTML escaping on interpolated full_name / company values',
    'Business Impact': 'Email HTML injection if an attacker signs up with <script>',
    'Current Approach': 'Inline HTML templates with template literals',
    'Replace With (Open Source)': 'MJML (OSS email framework) + handlebars with auto-escaping. Or Maizzle. Compile at build time.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Safe HTML rendering',
    Priority: 'Low',
    'Est. Effort': '3 days',
  },
  {
    ID: 'S9',
    Category: 'Security',
    Title: 'Secrets / error details may leak to logs',
    Severity: 'L',
    'Area / Component': 'Logging',
    'Files / Location': 'many console.error / console.warn sites',
    'Root Cause': 'No structured logger with redaction',
    'Business Impact': 'Gemini key hints / service account traces appear in provider logs',
    'Current Approach': 'Raw console.* with message + stack',
    'Replace With (Open Source)': 'pino (JSON logger) with redact patterns + OpenTelemetry OTLP export to SigNoz (OSS APM) or Loki + Grafana.',
    'Unlimited-Token Strategy': 'LLM-assisted post-processor to scan historical logs for leaked secrets and rotate them.',
    Rationale: 'Safe observability',
    Priority: 'Low',
    'Est. Effort': '3 days',
  },
  {
    ID: 'S10',
    Category: 'Security',
    Title: 'PII / financial fields unencrypted at rest',
    Severity: 'M',
    'Area / Component': 'Compliance',
    'Files / Location': 'leases, tenants, invoices, expenses tables',
    'Root Cause': 'Plain text columns',
    'Business Impact': 'GDPR / CCPA exposure if DB is breached',
    'Current Approach': 'Rely on Supabase encryption at rest (disk-level only)',
    'Replace With (Open Source)': 'Column-level encryption with pgcrypto (ships with Postgres). Key management via Infisical (OSS) or HashiCorp Vault OSS. Per-tenant DEK wrapped by a master KEK.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Enterprise compliance',
    Priority: 'Medium',
    'Est. Effort': '3 weeks',
  },
  {
    ID: 'S11',
    Category: 'Security',
    Title: 'Session tokens stored in localStorage',
    Severity: 'M',
    'Area / Component': 'Session',
    'Files / Location': 'Supabase client default + manual localStorage.removeItem in auth.js',
    'Root Cause': 'Supabase JS client default storage is localStorage',
    'Business Impact': 'XSS steals the token',
    'Current Approach': 'localStorage',
    'Replace With (Open Source)': 'Use supabase-ssr cookie-based storage (OSS, part of @supabase/ssr) with httpOnly + SameSite=strict + Secure.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Mitigates XSS token theft',
    Priority: 'Medium',
    'Est. Effort': '1 week',
  },
  {
    ID: 'S12',
    Category: 'Security',
    Title: 'No SSO / SAML / SCIM',
    Severity: 'H',
    'Area / Component': 'Enterprise auth',
    'Files / Location': 'N/A',
    'Root Cause': 'Only Google/Azure OAuth + email + MFA TOTP',
    'Business Impact': 'Blocks F500 procurement',
    'Current Approach': 'Supabase Auth providers only',
    'Replace With (Open Source)': 'Authentik OR Keycloak (both OSS) as an upstream IdP; federate into Supabase via OIDC. SCIM provisioning via Authentik SCIM app or Keycloak SCIM extension.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Enterprise sales blocker',
    Priority: 'Before enterprise scale',
    'Est. Effort': '4 weeks',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SHEET 4 — PERFORMANCE & SCALING
// ─────────────────────────────────────────────────────────────────────────────
const performance = [
  {
    ID: 'P1',
    Category: 'Performance',
    Title: '150s edge timeout too short for large PDFs',
    Severity: 'C',
    'Area / Component': 'Pipeline',
    'Files / Location': 'all parse-* / normalize-* / compute-* edge functions',
    'Root Cause': 'Supabase edge fn default limit; chained calls compound it',
    'Business Impact': 'Files > 20 pages routinely fail; customer churn',
    'Current Approach': 'Hope for the best + HTTP retry',
    'Replace With (Open Source)': 'Move workers off edge fns entirely → Deno/Node workers pulling from pg-boss or BullMQ with 15-minute job timeouts. Keep edge fns only for low-latency API calls.',
    'Unlimited-Token Strategy': 'Each job can afford a 100k+ token context call; no need to split large docs. Still parallelise across pages for wall-clock speed.',
    Rationale: 'Unblocks documents of any size',
    Priority: 'Immediate',
    'Est. Effort': '2–3 weeks',
  },
  {
    ID: 'P2',
    Category: 'Performance',
    Title: 'No explicit DB connection pooling config',
    Severity: 'M',
    'Area / Component': 'DB',
    'Files / Location': 'supabase project defaults',
    'Root Cause': 'Many edge fns each open a new service-role connection',
    'Business Impact': 'Connection exhaustion under load',
    'Current Approach': 'Supabase default pooler',
    'Replace With (Open Source)': 'Self-hosted PgBouncer in transaction-pooling mode; or PgCat (OSS, Rust) with read/write split. All free and mature.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Prevents connection storms',
    Priority: 'Medium',
    'Est. Effort': '1 week',
  },
  {
    ID: 'P3',
    Category: 'Performance',
    Title: 'Client api.js 30s in-memory cache + aggressive invalidation',
    Severity: 'M',
    'Area / Component': 'Client state',
    'Files / Location': 'src/services/api.js:272-299',
    'Root Cause': 'Home-grown cache alongside TanStack Query',
    'Business Impact': 'Stale views across tabs; hard-to-debug ghosts',
    'Current Approach': 'Module-local Map<string, {data, ts}>',
    'Replace With (Open Source)': 'Remove home-grown cache; standardise on TanStack Query (already installed; fully OSS). Shared queryKey conventions [\'lease\', orgId, id].',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Single source of client cache',
    Priority: 'Medium',
    'Est. Effort': '2 weeks',
  },
  {
    ID: 'P4',
    Category: 'Performance',
    Title: 'buildUserObject runs 3+ sequential SELECTs',
    Severity: 'M',
    'Area / Component': 'Login latency',
    'Files / Location': 'src/services/auth.js:234-308',
    'Root Cause': 'Separate queries for profile, memberships, org, then a second profile refetch',
    'Business Impact': '300–500ms added to first paint after login',
    'Current Approach': 'Sequential awaits',
    'Replace With (Open Source)': 'Single Postgres function get_user_context(user_id) returning JSON bundle; call via Supabase rpc(). All Postgres / all OSS.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'One round-trip',
    Priority: 'Medium',
    'Est. Effort': '2 days',
  },
  {
    ID: 'P5',
    Category: 'Performance',
    Title: 'getCurrentAccessScope pulls every property / lease per request',
    Severity: 'H',
    'Area / Component': 'RBAC',
    'Files / Location': 'src/services/api.js:107-220',
    'Root Cause': 'Builds accessible-ID sets by scanning the whole property+lease dataset',
    'Business Impact': 'Blows up at 10k+ properties',
    'Current Approach': 'Client-side set build with 30s cache',
    'Replace With (Open Source)': 'Materialised view user_accessible_properties refreshed via triggers; OR encode accessible property IDs into the JWT custom claims via a Supabase auth hook (OSS).',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Scale to large portfolios',
    Priority: 'High',
    'Est. Effort': '1 week',
  },
  {
    ID: 'P6',
    Category: 'Performance',
    Title: 'RLS helper functions do 3+ joins per row read',
    Severity: 'H',
    'Area / Component': 'DB performance',
    'Files / Location': 'migration 20260422000200_enterprise_access_control.sql',
    'Root Cause': 'can_access_property / can_read_page traverse memberships + user_access + properties every time',
    'Business Impact': 'Every SELECT on leases/expenses/etc pays the cost',
    'Current Approach': 'STABLE SECURITY DEFINER sql functions',
    'Replace With (Open Source)': 'Precompute access into session_gucs on JWT decode (hook in pgrst.pre_request); OR use Oso (OSS, Apache 2.0) for policy decisions cached per-request.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'RLS must stay fast',
    Priority: 'High',
    'Est. Effort': '2 weeks',
  },
  {
    ID: 'P7',
    Category: 'Performance',
    Title: '60-page Vite bundle with no code splitting',
    Severity: 'M',
    'Area / Component': 'Frontend perf',
    'Files / Location': 'src/pages.config.js imports all pages eagerly',
    'Root Cause': 'No React.lazy',
    'Business Impact': 'Large initial bundle; slow first paint',
    'Current Approach': 'All pages bundled into main chunk',
    'Replace With (Open Source)': 'React.lazy + Suspense for every route. Vite handles split points natively. Optionally use @tanstack/router for type-safe lazy routes.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Initial bundle < 300KB',
    Priority: 'Medium',
    'Est. Effort': '3 days',
  },
  {
    ID: 'P8',
    Category: 'Performance',
    Title: 'No queue for compute re-runs across many properties',
    Severity: 'H',
    'Area / Component': 'Compute',
    'Files / Location': 'supabase/functions/_shared/compute-orchestrator.ts',
    'Root Cause': 'Orchestrator triggers compute-* per-upload only; no batch re-compute entry',
    'Business Impact': 'Rules-change + mass re-compute scenarios are manual',
    'Current Approach': 'Manual triggers',
    'Replace With (Open Source)': 'pg-boss schedule API or River cron jobs; fan-out one job per property; worker pool consumes. All OSS.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Enables operational re-computes',
    Priority: 'High',
    'Est. Effort': '2 weeks',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SHEET 5 — AI / EXTRACTION / OCR
// ─────────────────────────────────────────────────────────────────────────────
const ai = [
  {
    ID: 'E1',
    Category: 'AI / Extraction',
    Title: 'Whole-file sent inline to Gemini when text is thin',
    Severity: 'H',
    'Area / Component': 'LLM extractor',
    'Files / Location': 'supabase/functions/_shared/extraction/llm-extractor.ts:266-281',
    'Root Cause': 'When rule+table find nothing, file is sent inline to Vertex as base64',
    'Business Impact': '50-page leases exceed token cap; content truncated silently',
    'Current Approach': 'callVertexAIFileJSON with whole file',
    'Replace With (Open Source)': 'Qwen2.5-VL-72B (Apache 2.0) or Llama 3.2 90B Vision served via vLLM; 1M-token context handles full leases. Primary extraction: Docling (MIT) + Marker (GPL) for layout + Surya OCR (GPL) for scanned text.',
    'Unlimited-Token Strategy': 'Send the WHOLE document (text + page images) in one call with the full extraction schema and 50 few-shot examples; no chunking required with 1M-ctx models. Run three times at temp 0, 0.2, 0.4 → take majority vote.',
    Rationale: 'No truncation; highest accuracy; no vendor cost',
    Priority: 'High',
    'Est. Effort': '3 weeks',
  },
  {
    ID: 'E2',
    Category: 'AI / Extraction',
    Title: 'Gemini OCR output capped at 8–16K tokens',
    Severity: 'H',
    'Area / Component': 'OCR',
    'Files / Location': 'supabase/functions/_shared/ocr/vision-ocr.ts:56-133',
    'Root Cause': 'maxOutputTokens=8192 or 16384',
    'Business Impact': 'Long scanned leases lose content',
    'Current Approach': 'Single Gemini Vision call per document',
    'Replace With (Open Source)': 'Surya OCR (GPL, SOTA open OCR) + MinerU (AGPL, full-doc parser) + Nougat (MIT, for tables/maths). Combine with Marker for markdown-quality output. Everything local, no token cap.',
    'Unlimited-Token Strategy': 'Page-by-page Surya → per-page LLM clean-up with Qwen2.5-72B → structured merge. Unlimited output; no truncation.',
    Rationale: 'Open, local, no cap',
    Priority: 'High',
    'Est. Effort': '3 weeks',
  },
  {
    ID: 'E3',
    Category: 'AI / Extraction',
    Title: 'Docling optional but tables degrade when off',
    Severity: 'M',
    'Area / Component': 'Tables',
    'Files / Location': 'supabase/functions/_shared/extraction/parser.ts pickStrategy',
    'Root Cause': 'DOCLING_API_URL optional; without it, rent roll rows break',
    'Business Impact': 'Rent roll parsing flaky',
    'Current Approach': 'Vision fallback returns a text blob',
    'Replace With (Open Source)': 'Self-host Docling (MIT license); always-on. Add PaddleOCR table-structure or TableTransformer (both OSS) as a second opinion.',
    'Unlimited-Token Strategy': 'Feed both Docling and Vision outputs to a reasoning LLM (DeepSeek V3 or Llama 3.3 70B) and let it produce the canonical table with reasoning.',
    Rationale: 'Tables are core to CRE docs',
    Priority: 'High',
    'Est. Effort': '2 weeks',
  },
  {
    ID: 'E4',
    Category: 'AI / Extraction',
    Title: 'Deprecated extract-document-fields vs live extract-lease — two paths',
    Severity: 'L',
    'Area / Component': 'Pipeline hygiene',
    'Files / Location': 'supabase/functions/extract-document-fields + extract-lease',
    'Root Cause': 'Old endpoints left live',
    'Business Impact': 'Accidental regressions to the old path',
    'Current Approach': 'extract-document-fields returns 410; extract-lease still live',
    'Replace With (Open Source)': 'Remove extract-lease; all extraction flows through ingest-file → pipeline. Clean up.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'One canonical path',
    Priority: 'Low',
    'Est. Effort': '1 day',
  },
  {
    ID: 'E5',
    Category: 'AI / Extraction',
    Title: 'parsingEngine.js duplicates CSV logic in the client',
    Severity: 'M',
    'Area / Component': 'Parsing',
    'Files / Location': 'src/services/parsingEngine.js (1,511 LOC)',
    'Root Cause': 'Client-side CSV parser drifted from server',
    'Business Impact': 'Column maps differ; import results differ',
    'Current Approach': 'Two parsers',
    'Replace With (Open Source)': 'Delete the client parser. Use Papa Parse (MIT) just for client preview; actual parsing happens server-side in edge fn via csv-parse (MIT).',
    'Unlimited-Token Strategy': 'With unlimited tokens, bypass CSV entirely — feed the raw bytes to an LLM with a schema and let it emit normalised rows. (Same cost as today because it is free.)',
    Rationale: 'Remove 1,500 LOC of drift risk',
    Priority: 'Medium',
    'Est. Effort': '1 week',
  },
  {
    ID: 'E6',
    Category: 'AI / Extraction',
    Title: 'LLM confidence hardcoded at 0.70',
    Severity: 'L',
    'Area / Component': 'Confidence display',
    'Files / Location': 'supabase/functions/_shared/extraction/llm-extractor.ts',
    'Root Cause': 'Static value',
    'Business Impact': 'UI confidence badges are meaningless',
    'Current Approach': 'confidence: 0.70',
    'Replace With (Open Source)': 'Use logprobs from vLLM/llama.cpp (both expose per-token logprobs) to compute real confidence. OR run an LLM-as-judge self-critique pass that scores each field 0–1.',
    'Unlimited-Token Strategy': 'Self-consistency: run extraction 5 times at varying temperatures; agreement rate = confidence.',
    Rationale: 'Accurate UI signal',
    Priority: 'Low',
    'Est. Effort': '3 days',
  },
  {
    ID: 'E7',
    Category: 'AI / Extraction',
    Title: 'Manual-review fallback fills the grid with nulls',
    Severity: 'M',
    'Area / Component': 'UX',
    'Files / Location': 'supabase/functions/ingest-file/index.ts:186-269',
    'Root Cause': 'On extraction failure, payload has every standard field = null',
    'Business Impact': 'User sees empty grid; no clue what to do',
    'Current Approach': 'Static field list with nulls',
    'Replace With (Open Source)': 'Keep any partial rule/table outputs in the payload; surface extraction errors inline; show a thumbnail preview (rendered via pdf.js, MIT).',
    'Unlimited-Token Strategy': 'Even on failure, make one final Hail-Mary LLM call with the whole doc and the full schema — it is free. Present best-guess values as suggestions.',
    Rationale: 'Turns failure into a useful form',
    Priority: 'Medium',
    'Est. Effort': '1 week',
  },
  {
    ID: 'E8',
    Category: 'AI / Extraction',
    Title: 'No schema-constrained LLM output',
    Severity: 'M',
    'Area / Component': 'Reliability',
    'Files / Location': 'llm-extractor.ts, ocr/vision-ocr.ts',
    'Root Cause': 'Relies on "return JSON" prompt rule + markdown-fence stripping',
    'Business Impact': 'Malformed JSON returned occasionally',
    'Current Approach': 'parseLLMResponse returns null on failure',
    'Replace With (Open Source)': 'Outlines (Apache 2.0) OR llguidance OR xgrammar — grammar-constrained decoding forces valid JSON matching a pydantic/zod schema. Native support in vLLM and llama.cpp.',
    'Unlimited-Token Strategy': 'N/A — deterministic grammar is better than any token budget',
    Rationale: 'JSON always parses',
    Priority: 'Medium',
    'Est. Effort': '1 week',
  },
  {
    ID: 'E9',
    Category: 'AI / Extraction',
    Title: 'Extraction prompt has no domain examples / few-shot',
    Severity: 'M',
    'Area / Component': 'Prompt engineering',
    'Files / Location': 'llm-extractor.ts LLM_SYSTEM_PROMPT',
    'Root Cause': 'System prompt is instructions only',
    'Business Impact': 'Edge-case lease terms extracted poorly',
    'Current Approach': 'Zero-shot',
    'Replace With (Open Source)': 'Build a CRE few-shot bank in the repo (N=50+ examples per subtype). Retrieve top-k similar via pgvector + bge-large-en (MIT).',
    'Unlimited-Token Strategy': 'Always include ALL examples (thousands of tokens) — it is free. Quality goes up.',
    Rationale: 'Dramatic accuracy improvement for lease edge cases',
    Priority: 'High',
    'Est. Effort': '2 weeks',
  },
  {
    ID: 'E10',
    Category: 'AI / Extraction',
    Title: 'No human-in-the-loop feedback captured back into prompts',
    Severity: 'M',
    'Area / Component': 'ML ops',
    'Files / Location': 'review-approve + normalize-pdf-output',
    'Root Cause': 'review-approve saves reviewed_output but nothing feeds it back',
    'Business Impact': 'Extraction quality never improves',
    'Current Approach': 'Reviews are write-only',
    'Replace With (Open Source)': 'Argilla (Apache 2.0) or Label Studio (Apache 2.0) for review tracking; on each approval, store the (field, before, after) diff; use diffs as training data for fine-tuning a local LoRA adapter via Axolotl (Apache 2.0).',
    'Unlimited-Token Strategy': 'Also prepend the most relevant corrections as few-shot in subsequent extractions for the same tenant / landlord.',
    Rationale: 'Self-improving system',
    Priority: 'Medium',
    'Est. Effort': '4 weeks',
  },
  {
    ID: 'E11',
    Category: 'AI / Extraction',
    Title: 'No OCR / extraction observability',
    Severity: 'M',
    'Area / Component': 'Monitoring',
    'Files / Location': 'entire extraction pipeline',
    'Root Cause': 'console.log only',
    'Business Impact': 'Cannot see field-level accuracy trends',
    'Current Approach': 'Ad-hoc logs',
    'Replace With (Open Source)': 'Langfuse (MIT, self-hostable) or Phoenix Arize (Elastic license, OSS) for LLM tracing; OpenLLMetry for OTel integration. Dashboards: Grafana (OSS).',
    'Unlimited-Token Strategy': 'Log every prompt+response; keep forever (storage is cheap); diff when models change.',
    Rationale: 'Model and prompt iteration',
    Priority: 'Medium',
    'Est. Effort': '1 week',
  },
  {
    ID: 'E12',
    Category: 'AI / Extraction',
    Title: 'Vertex AI vendor lock-in',
    Severity: 'H',
    'Area / Component': 'Vendor',
    'Files / Location': '_shared/vertex-ai.ts, ocr/vision-ocr.ts',
    'Root Cause': 'Core extraction is GCP-only',
    'Business Impact': 'Uncontrollable costs; no offline / on-prem option for enterprise tenants',
    'Current Approach': 'Vertex AI Gemini 2.5 Flash',
    'Replace With (Open Source)': 'vLLM (Apache 2.0) or SGLang (Apache 2.0) serving Qwen2.5-VL-72B, Llama 3.3 70B, DeepSeek V3. Ollama for dev. OpenAI-compatible API so code changes are minimal.',
    'Unlimited-Token Strategy': 'Own the GPUs; unlimited calls; can run 3-model ensembles per extraction; can do page-level parallelism without cost worry.',
    Rationale: 'Cost, sovereignty, accuracy',
    Priority: 'High',
    'Est. Effort': '4–6 weeks (infra)',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SHEET 6 — FRONTEND / UX
// ─────────────────────────────────────────────────────────────────────────────
const frontend = [
  {
    ID: 'F1',
    Category: 'Frontend',
    Title: 'No code-splitting — 60 pages bundled together',
    Severity: 'M',
    'Area / Component': 'Perf',
    'Files / Location': 'src/pages.config.js',
    'Root Cause': 'Eager imports',
    'Business Impact': 'Big initial bundle',
    'Current Approach': 'All pages imported upfront',
    'Replace With (Open Source)': 'React.lazy (built-in) + Vite auto-splits. Optionally TanStack Router (MIT) for typed lazy routes.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Faster first paint',
    Priority: 'Medium',
    'Est. Effort': '3 days',
  },
  {
    ID: 'F2',
    Category: 'Frontend',
    Title: 'ErrorBoundary at root only',
    Severity: 'M',
    'Area / Component': 'Resilience',
    'Files / Location': 'src/App.jsx:18-54',
    'Root Cause': 'Single top-level boundary',
    'Business Impact': 'One page error crashes the whole app',
    'Current Approach': 'Top-level ErrorBoundary class',
    'Replace With (Open Source)': 'react-error-boundary (MIT) per-route + Sentry-compatible open source error tracker GlitchTip (MIT) or self-hosted Sentry OSS.',
    'Unlimited-Token Strategy': 'An LLM agent triages incoming errors nightly and opens PRs with fixes.',
    Rationale: 'Graceful degradation',
    Priority: 'Medium',
    'Est. Effort': '3 days',
  },
  {
    ID: 'F3',
    Category: 'Frontend',
    Title: 'Auth state machine is a giant if/else',
    Severity: 'H',
    'Area / Component': 'Routing',
    'Files / Location': 'src/App.jsx:362-462',
    'Root Cause': 'Organic growth',
    'Business Impact': 'Fragile to extend; regressions common',
    'Current Approach': 'Nested conditionals + hand-written guards',
    'Replace With (Open Source)': 'XState (MIT) — model Unauthenticated / PendingApproval / OnboardingInProgress / ActiveDashboard as explicit states with guarded transitions. Visualisable in @xstate/inspect.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Eliminates a whole class of routing bugs',
    Priority: 'High',
    'Est. Effort': '2 weeks',
  },
  {
    ID: 'F4',
    Category: 'Frontend',
    Title: 'useEffect + manual fetch everywhere',
    Severity: 'M',
    'Area / Component': 'Data loading',
    'Files / Location': 'most pages',
    'Root Cause': 'TanStack Query is installed but not consistently used',
    'Business Impact': 'Race conditions, memory leaks, flicker',
    'Current Approach': 'Hand-rolled',
    'Replace With (Open Source)': 'TanStack Query v5 (MIT). Already installed. Standard queryKey conventions.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Battle-tested solution to every issue these pages have',
    Priority: 'Medium',
    'Est. Effort': '3 weeks',
  },
  {
    ID: 'F5',
    Category: 'Frontend',
    Title: 'No i18n, missing html lang',
    Severity: 'L',
    'Area / Component': 'A11y / global',
    'Files / Location': 'index.html, all pages',
    'Root Cause': 'Never planned for',
    'Business Impact': 'No localisation; screen-reader language detection broken',
    'Current Approach': 'English hardcoded',
    'Replace With (Open Source)': 'i18next (MIT) + react-i18next; locale files committed to repo.',
    'Unlimited-Token Strategy': 'LLM auto-translates all strings to all target locales on every merge; QA\'d by native speakers.',
    Rationale: 'Future-proof for international expansion',
    Priority: 'Low',
    'Est. Effort': '2 weeks',
  },
  {
    ID: 'F6',
    Category: 'Frontend',
    Title: 'Build logs and lint outputs checked into repo',
    Severity: 'L',
    'Area / Component': 'Hygiene',
    'Files / Location': 'build*.txt, eslint*.log, lint_*.txt',
    'Root Cause': 'Accidental git add',
    'Business Impact': 'Repo noise',
    'Current Approach': 'Files committed',
    'Replace With (Open Source)': 'Delete + .gitignore',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Cleanup',
    Priority: 'Low',
    'Est. Effort': '1 hour',
  },
  {
    ID: 'F7',
    Category: 'Frontend',
    Title: 'No a11y audit',
    Severity: 'M',
    'Area / Component': 'UX / legal',
    'Files / Location': 'all pages',
    'Root Cause': 'Never done',
    'Business Impact': 'WCAG non-compliance; enterprise RFP blocker',
    'Current Approach': 'None',
    'Replace With (Open Source)': 'axe-core (MPL 2.0) via @axe-core/react in dev + Pa11y (LGPL) in CI. storybook-addon-a11y (MIT) per component.',
    'Unlimited-Token Strategy': 'LLM-assisted fix-suggest for every axe violation.',
    Rationale: 'A11y is mandatory for most enterprise customers',
    Priority: 'Medium',
    'Est. Effort': '3 weeks',
  },
  {
    ID: 'F8',
    Category: 'Frontend',
    Title: 'Heavy deps: three.js, react-leaflet, framer-motion, jspdf, html2canvas, xlsx, mammoth',
    Severity: 'L',
    'Area / Component': 'Bundle',
    'Files / Location': 'package.json',
    'Root Cause': 'Accumulated features',
    'Business Impact': 'Large bundle; slow cold start',
    'Current Approach': 'All eager',
    'Replace With (Open Source)': 'Lazy-load them; for PDF export consider pdf-lib (MIT) in a worker; for xlsx consider exceljs (MIT).',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Cut bundle by 30%+',
    Priority: 'Low',
    'Est. Effort': '1 week',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SHEET 7 — BACKEND / DB / MIGRATIONS
// ─────────────────────────────────────────────────────────────────────────────
const backend = [
  {
    ID: 'B1',
    Category: 'Backend / DB',
    Title: '54 migrations, IF NOT EXISTS everywhere — cannot recreate from scratch',
    Severity: 'H',
    'Area / Component': 'Schema management',
    'Files / Location': 'supabase/migrations/',
    'Root Cause': 'Additive-only migration style; heavy DROP POLICY IF EXISTS / CREATE POLICY cycles',
    'Business Impact': 'Fresh env bootstrap is unreliable; unclear schema truth',
    'Current Approach': '54 files applied top-to-bottom',
    'Replace With (Open Source)': 'sqitch (MIT) OR Atlas (Apache 2.0) OR Flyway Community Edition (Apache 2.0) for versioned migrations. Squash current 54 into baseline + forward-only going forward.',
    'Unlimited-Token Strategy': 'LLM-generated squash: feed it the 54 files, let it emit baseline + test that `supabase db reset` yields identical schema.',
    Rationale: 'Reproducible environments',
    Priority: 'High',
    'Est. Effort': '2 weeks',
  },
  {
    ID: 'B2',
    Category: 'Backend / DB',
    Title: 'db_schema.sql (3,421 LOC) out of sync with migrations',
    Severity: 'H',
    'Area / Component': 'Schema docs',
    'Files / Location': 'db_schema.sql',
    'Root Cause': 'Dumped once, never regenerated',
    'Business Impact': 'Confusion about source of truth',
    'Current Approach': 'Stale dump',
    'Replace With (Open Source)': 'Regenerate via pg_dump --schema-only in CI nightly; commit to git for diffability. Optional: SchemaSpy (Apache 2.0) for HTML docs.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Docs = truth',
    Priority: 'Medium',
    'Est. Effort': '1 day',
  },
  {
    ID: 'B3',
    Category: 'Backend / DB',
    Title: 'Mixed date types (TEXT vs DATE)',
    Severity: 'M',
    'Area / Component': 'Data quality',
    'Files / Location': 'multiple migrations',
    'Root Cause': 'Incremental additions',
    'Business Impact': 'Casting bugs in compute engines',
    'Current Approach': 'Both types coexist',
    'Replace With (Open Source)': 'Migration: normalise to DATE with explicit cast + default; update all compute fns. Standard Postgres.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Correctness',
    Priority: 'Medium',
    'Est. Effort': '1 week',
  },
  {
    ID: 'B4',
    Category: 'Backend / DB',
    Title: 'notifications + audit_logs exempt from org scoping',
    Severity: 'M',
    'Area / Component': 'Tenancy',
    'Files / Location': 'src/types/index.js:70-76 ORG_EXEMPT_TABLES',
    'Root Cause': 'Historical decision to mark them global',
    'Business Impact': 'Cross-tenant visibility possible',
    'Current Approach': 'Exempt from org filter',
    'Replace With (Open Source)': 'Make them org-scoped; super admin sees all via RLS helper is_super_admin(); super admin UI aggregates across orgs explicitly.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Tenancy consistency',
    Priority: 'Medium',
    'Est. Effort': '3 days',
  },
  {
    ID: 'B5',
    Category: 'Backend / DB',
    Title: 'In-memory fallback on PGRST205 masks schema drift',
    Severity: 'H',
    'Area / Component': 'Error handling',
    'Files / Location': 'src/services/api.js isTableNotFound',
    'Root Cause': 'DEV mode seed store accidentally used in production paths',
    'Business Impact': 'Prod errors look like success; users think data was saved',
    'Current Approach': 'Silently fall back to memoryStore on table-not-found',
    'Replace With (Open Source)': 'Gate the fallback behind import.meta.env.DEV; in prod throw and log to GlitchTip / self-hosted Sentry OSS.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Don\'t hide prod errors',
    Priority: 'High',
    'Est. Effort': '1 day',
  },
  {
    ID: 'B6',
    Category: 'Backend / DB',
    Title: 'logAudit is best-effort (no retry, no transaction)',
    Severity: 'L',
    'Area / Component': 'Audit',
    'Files / Location': 'src/services/audit.js + api.js',
    'Root Cause': 'Fire-and-forget .catch(() => {})',
    'Business Impact': 'Missing audit entries for compliance',
    'Current Approach': 'logAudit(...).catch(noop)',
    'Replace With (Open Source)': 'Write audit inside the same SQL transaction via a Postgres trigger on every tenant table; all-or-nothing.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Audit is compliance-critical',
    Priority: 'Medium',
    'Est. Effort': '1 week',
  },
  {
    ID: 'B7',
    Category: 'Backend / DB',
    Title: 'Storage bucket has no retention / lifecycle policy',
    Severity: 'M',
    'Area / Component': 'Storage',
    'Files / Location': 'financial-uploads bucket',
    'Root Cause': 'Never configured',
    'Business Impact': 'PII retained indefinitely; GDPR issue',
    'Current Approach': 'Indefinite retention',
    'Replace With (Open Source)': 'MinIO (AGPL, S3-compatible, self-hostable) with lifecycle rules OR self-hosted SeaweedFS. Retention policy per tenant.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Compliance + cost',
    Priority: 'Medium',
    'Est. Effort': '1 week',
  },
  {
    ID: 'B8',
    Category: 'Backend / DB',
    Title: 'No backup verification / DR runbook',
    Severity: 'H',
    'Area / Component': 'DR',
    'Files / Location': 'N/A',
    'Root Cause': 'Relying on Supabase defaults',
    'Business Impact': 'Can\'t prove RTO/RPO to enterprise customers',
    'Current Approach': 'Implicit Supabase backups',
    'Replace With (Open Source)': 'pgBackRest (MIT) or Barman (GPL) + WAL streaming to MinIO. Monthly restore-drill automation.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Enterprise DR posture',
    Priority: 'High',
    'Est. Effort': '3 weeks',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SHEET 8 — AUTH / ACCESS / OBSERVABILITY
// ─────────────────────────────────────────────────────────────────────────────
const observability = [
  {
    ID: 'O1',
    Category: 'Observability',
    Title: 'No APM / error tracker',
    Severity: 'H',
    'Area / Component': 'Obs',
    'Files / Location': 'all',
    'Root Cause': 'Never added',
    'Business Impact': 'Cannot diagnose prod issues',
    'Current Approach': 'console.log',
    'Replace With (Open Source)': 'SigNoz (MIT) full-stack APM + GlitchTip (MIT) error tracker + OpenTelemetry SDKs (Apache 2.0) in frontend and edge fns. All OTLP-native.',
    'Unlimited-Token Strategy': 'LLM-based incident triage agent summarises anomaly clusters and auto-opens tickets.',
    Rationale: 'Cannot run a prod SaaS without this',
    Priority: 'Immediate',
    'Est. Effort': '1 week',
  },
  {
    ID: 'O2',
    Category: 'Observability',
    Title: 'Unstructured logging',
    Severity: 'M',
    'Area / Component': 'Logs',
    'Files / Location': 'everywhere',
    'Root Cause': 'console.log',
    'Business Impact': 'Cannot query by org_id / file_id',
    'Current Approach': 'Unstructured',
    'Replace With (Open Source)': 'pino (MIT) on frontend, deno structured log on edge fns; ship to Loki (AGPL) + Grafana (AGPL). Enforce {org_id, user_id, file_id, request_id} on every line.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Queryable observability',
    Priority: 'Medium',
    'Est. Effort': '1 week',
  },
  {
    ID: 'O3',
    Category: 'Observability',
    Title: 'compute_runs + pipeline_logs tables unused by operators',
    Severity: 'M',
    'Area / Component': 'Admin UI',
    'Files / Location': 'DB tables + no admin view',
    'Root Cause': 'Tables exist; no dashboard consumes them',
    'Business Impact': 'Admins cannot see pipeline health',
    'Current Approach': 'Rows written but unread',
    'Replace With (Open Source)': 'Grafana dashboards reading Postgres directly via the Postgres data source (Apache 2.0). Panels: jobs by status, p95 duration, retries per engine, failure reasons.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Operational visibility',
    Priority: 'Medium',
    'Est. Effort': '3 days',
  },
  {
    ID: 'O4',
    Category: 'Observability',
    Title: 'No health checks / uptime monitoring',
    Severity: 'M',
    'Area / Component': 'Obs',
    'Files / Location': 'N/A',
    'Root Cause': 'Not set up',
    'Business Impact': 'Silent outages',
    'Current Approach': 'None',
    'Replace With (Open Source)': 'Uptime Kuma (MIT, self-hosted) + Cachet (BSD-3) status page. Synthetic probes hitting every edge fn every minute.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Detect outages before customers do',
    Priority: 'Medium',
    'Est. Effort': '1 day',
  },
  {
    ID: 'O5',
    Category: 'Compliance',
    Title: 'No GDPR data-export / right-to-be-forgotten endpoint',
    Severity: 'H',
    'Area / Component': 'Compliance',
    'Files / Location': 'N/A',
    'Root Cause': 'Feature never built',
    'Business Impact': 'Hard legal/enterprise blocker',
    'Current Approach': 'None',
    'Replace With (Open Source)': 'Build export-user-data + purge-user-data edge fns. Use Postgres pg_dump --data-only scoped by user_id + org_id. Store exports in MinIO (AGPL) with time-limited signed URLs.',
    'Unlimited-Token Strategy': 'LLM-based PII scrubber to anonymise exports where regulation requires.',
    Rationale: 'GDPR/CCPA compliance',
    Priority: 'High',
    'Est. Effort': '3 weeks',
  },
  {
    ID: 'O6',
    Category: 'Auth',
    Title: 'Custom roles (role_definitions table) not wired to UI',
    Severity: 'M',
    'Area / Component': 'RBAC',
    'Files / Location': 'migration 20260422000200 role_definitions; no UI',
    'Root Cause': 'Table exists, no editor',
    'Business Impact': 'Tenants cannot define custom roles',
    'Current Approach': 'Hardcoded ROLE_PAGES + ROLE_ALIASES in rbac.js',
    'Replace With (Open Source)': 'Build /UserManagement/Roles editor in React; persist to role_definitions. Rules engine: Casbin (Apache 2.0) or Cedar (Apache 2.0).',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Enterprise differentiator',
    Priority: 'High',
    'Est. Effort': '3 weeks',
  },
  {
    ID: 'O7',
    Category: 'Auth',
    Title: 'Role aliases hardcoded in frontend only',
    Severity: 'L',
    'Area / Component': 'RBAC',
    'Files / Location': 'src/lib/rbac.js ROLE_ALIASES',
    'Root Cause': 'JS object literal',
    'Business Impact': 'Aliases not enforced in DB / edge fns',
    'Current Approach': 'asset_manager → manager in JS',
    'Replace With (Open Source)': 'Push aliases into role_definitions table with parent_role_key. RLS helpers check alias chain.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Source of truth',
    Priority: 'Low',
    'Est. Effort': '1 week',
  },
  {
    ID: 'O8',
    Category: 'Auth',
    Title: 'No impersonation / admin-as-tenant support tooling',
    Severity: 'M',
    'Area / Component': 'Support ops',
    'Files / Location': 'N/A',
    'Root Cause': 'Not built',
    'Business Impact': 'Support cannot reproduce customer issues',
    'Current Approach': 'Only via DB access',
    'Replace With (Open Source)': 'Time-boxed impersonation token issued by super-admin action; every impersonated request flagged in permission_audit_events. No vendor needed.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Cuts support time dramatically',
    Priority: 'Medium',
    'Est. Effort': '2 weeks',
  },
  {
    ID: 'O9',
    Category: 'Compliance',
    Title: 'No audit-log retention policy or archival',
    Severity: 'M',
    'Area / Component': 'Compliance',
    'Files / Location': 'audit_logs table',
    'Root Cause': 'Never set',
    'Business Impact': 'DB bloat; cannot prove retention compliance',
    'Current Approach': 'Grows forever',
    'Replace With (Open Source)': 'pg_partman (PostgreSQL License, ≈BSD) monthly partitions; ship cold partitions to MinIO via pg_dump; query via ClickHouse (Apache 2.0) for long-range analytics.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Audit scale + compliance',
    Priority: 'Medium',
    'Est. Effort': '2 weeks',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SHEET 9 — REPLACE / REDESIGN
// ─────────────────────────────────────────────────────────────────────────────
const replace = [
  {
    ID: 'R1',
    Category: 'Replacement',
    Title: 'HTTP-chained edge functions → open-source queue',
    Severity: 'C',
    'Area / Component': 'Pipeline',
    'Files / Location': 'all doc pipeline fns',
    'Root Cause': 'Synchronous composition',
    'Business Impact': 'Core product reliability',
    'Current Approach': 'ingest-file orchestrates via HTTP',
    'Replace With (Open Source)': 'pg-boss (MIT) for Postgres-native queueing; Temporal OSS (MIT) for complex workflows; River (MIT) for Go-based workers. All self-host.',
    'Unlimited-Token Strategy': 'Each job does one big LLM pass; no need to split extraction into micro-steps.',
    Rationale: 'Foundation for everything else',
    Priority: 'Immediate',
    'Est. Effort': '3 weeks',
  },
  {
    ID: 'R2',
    Category: 'Replacement',
    Title: 'Duplicated CAM/budget engines → shared TypeScript package',
    Severity: 'H',
    'Area / Component': 'Business logic',
    'Files / Location': 'src/services/*Engine.js + supabase/functions/_shared/cam-calculator.ts',
    'Root Cause': 'Parallel development',
    'Business Impact': 'Financial correctness risk',
    'Current Approach': 'Two codebases',
    'Replace With (Open Source)': 'pnpm workspace (MIT) with @cre/engines package imported both in Vite build and in Deno via import maps.',
    'Unlimited-Token Strategy': 'LLM generates property-based tests (fast-check, MIT) for every engine.',
    Rationale: 'Single source of truth',
    Priority: 'High',
    'Est. Effort': '2 weeks',
  },
  {
    ID: 'R3',
    Category: 'Replacement',
    Title: 'user_access + member_* → unified scope grants table',
    Severity: 'H',
    'Area / Component': 'RBAC',
    'Files / Location': 'migrations 20260408 + 20260422000200',
    'Root Cause': 'Schema evolution without cleanup',
    'Business Impact': 'Dual-write bugs',
    'Current Approach': 'Both live',
    'Replace With (Open Source)': 'Drop the legacy table after migrating data; rewrite RLS helpers to use only member_*.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Unblocks clean ABAC',
    Priority: 'High',
    'Est. Effort': '1 week',
  },
  {
    ID: 'R4',
    Category: 'Replacement',
    Title: 'Hand-written routing state machine → XState',
    Severity: 'M',
    'Area / Component': 'Frontend',
    'Files / Location': 'src/App.jsx',
    'Root Cause': 'Organic growth',
    'Business Impact': 'Fragile',
    'Current Approach': 'Conditionals',
    'Replace With (Open Source)': 'XState v5 (MIT).',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Testable, visualisable',
    Priority: 'Medium',
    'Est. Effort': '2 weeks',
  },
  {
    ID: 'R5',
    Category: 'Replacement',
    Title: 'api.js allow-lists → generated Supabase types',
    Severity: 'H',
    'Area / Component': 'Type safety',
    'Files / Location': 'src/services/api.js ALLOWED_COLUMNS',
    'Root Cause': 'Manual maintenance',
    'Business Impact': 'Drift = silent data loss',
    'Current Approach': 'Hand-maintained Sets',
    'Replace With (Open Source)': 'supabase gen types typescript --local > types/supabase.ts in CI; Zod schemas auto-generated via zod-to-openapi / kysely-codegen (both MIT).',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'No drift',
    Priority: 'High',
    'Est. Effort': '1 week',
  },
  {
    ID: 'R6',
    Category: 'Replacement',
    Title: 'Client CSV parser → server-only parsing',
    Severity: 'M',
    'Area / Component': 'Parsing',
    'Files / Location': 'src/services/parsingEngine.js',
    'Root Cause': 'Historical',
    'Business Impact': 'Column-map drift',
    'Current Approach': 'Big client parser',
    'Replace With (Open Source)': 'csv-parse (MIT) on the server; PapaParse (MIT) only for client preview.',
    'Unlimited-Token Strategy': 'With unlimited tokens, skip CSV entirely: upload the file, LLM parses it against the schema.',
    Rationale: 'One parser',
    Priority: 'Medium',
    'Est. Effort': '1 week',
  },
  {
    ID: 'R7',
    Category: 'Replacement',
    Title: 'Gemini Flash → self-hosted large-context open models',
    Severity: 'H',
    'Area / Component': 'AI',
    'Files / Location': '_shared/vertex-ai.ts + ocr/vision-ocr.ts',
    'Root Cause': 'Vendor dependency',
    'Business Impact': 'Cost, accuracy ceiling, lock-in',
    'Current Approach': 'Gemini 2.5 Flash',
    'Replace With (Open Source)': 'vLLM (Apache 2.0) or SGLang (Apache 2.0) serving Qwen2.5-VL-72B for vision, Llama 3.3 70B / DeepSeek V3 for text reasoning, Qwen2.5-1M for long-context lease work. OpenAI-compatible endpoints.',
    'Unlimited-Token Strategy': 'Own GPUs → every request uses the biggest model with full context; ensemble voting for financial fields.',
    Rationale: 'Sovereignty, cost, accuracy',
    Priority: 'High',
    'Est. Effort': '4–6 weeks',
  },
  {
    ID: 'R8',
    Category: 'Replacement',
    Title: 'mapRow switch in store-data → generated from schema',
    Severity: 'M',
    'Area / Component': 'Pipeline',
    'Files / Location': 'supabase/functions/store-data/index.ts',
    'Root Cause': 'Hand-maintained mapping',
    'Business Impact': 'Every new field = 3 file edits',
    'Current Approach': 'switch (moduleType) { ... }',
    'Replace With (Open Source)': 'Generate mapRow from extraction schemas + Supabase types; ajv (MIT) for validation; one config file drives everything.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'DRY',
    Priority: 'Medium',
    'Est. Effort': '1 week',
  },
  {
    ID: 'R9',
    Category: 'Replacement',
    Title: 'Hardcoded ROLE_ALIASES → role_definitions table + policy engine',
    Severity: 'H',
    'Area / Component': 'RBAC',
    'Files / Location': 'src/lib/rbac.js',
    'Root Cause': 'Historical',
    'Business Impact': 'Cannot offer custom roles per tenant',
    'Current Approach': 'JS object literal',
    'Replace With (Open Source)': 'Casbin (Apache 2.0) with Postgres adapter OR Cedar (Apache 2.0) via cedar-policy crate exposed as WASM in edge fns.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Enterprise RBAC',
    Priority: 'High',
    'Est. Effort': '4 weeks',
  },
  {
    ID: 'R10',
    Category: 'Replacement',
    Title: 'db_schema.sql stale → regenerated in CI',
    Severity: 'L',
    'Area / Component': 'Docs',
    'Files / Location': 'db_schema.sql',
    'Root Cause': 'One-off dump',
    'Business Impact': 'Docs mislead engineers',
    'Current Approach': 'Manual file',
    'Replace With (Open Source)': 'pg_dump nightly + SchemaSpy (Apache 2.0) visualisations.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Docs = truth',
    Priority: 'Low',
    'Est. Effort': '1 day',
  },
  {
    ID: 'R11',
    Category: 'Replacement',
    Title: 'localStorage session → httpOnly cookies via supabase-ssr',
    Severity: 'M',
    'Area / Component': 'Security',
    'Files / Location': 'Supabase client config',
    'Root Cause': 'Default storage',
    'Business Impact': 'XSS token theft risk',
    'Current Approach': 'localStorage',
    'Replace With (Open Source)': '@supabase/ssr (MIT) cookie adapter.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Defence in depth',
    Priority: 'Medium',
    'Est. Effort': '1 week',
  },
  {
    ID: 'R12',
    Category: 'Replacement',
    Title: 'Service-role key everywhere → segmented Postgres roles',
    Severity: 'M',
    'Area / Component': 'Security',
    'Files / Location': '_shared/supabase.ts',
    'Root Cause': 'Simplicity',
    'Business Impact': 'Blast radius',
    'Current Approach': 'One key',
    'Replace With (Open Source)': 'Per-edge-fn Postgres role + JWT; least privilege.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Defence in depth',
    Priority: 'Medium',
    'Est. Effort': '2 weeks',
  },
  {
    ID: 'R13',
    Category: 'Replacement',
    Title: 'Snapshot tables → event-sourced financial ledger',
    Severity: 'M',
    'Area / Component': 'Finance',
    'Files / Location': 'cam_calculations, budgets, revenues, actuals',
    'Root Cause': 'Current design stores only latest',
    'Business Impact': 'Cannot answer "why did this number change?"',
    'Current Approach': 'Snapshot + overwrite',
    'Replace With (Open Source)': 'EventStore (Apache 2.0) OR Postgres + append-only financial_events table with projections rebuilt via materialised views. Pair with Debezium (Apache 2.0) for CDC if needed.',
    'Unlimited-Token Strategy': 'LLM agent answers natural-language "explain this variance" queries by reading the event stream.',
    Rationale: 'True auditability',
    Priority: 'Before enterprise scale',
    'Est. Effort': '8 weeks',
  },
  {
    ID: 'R14',
    Category: 'Replacement',
    Title: 'Resend → self-hosted transactional mail',
    Severity: 'M',
    'Area / Component': 'Email',
    'Files / Location': 'signup/index.ts, invite-user/index.ts, send-email/index.ts',
    'Root Cause': 'SaaS dependency',
    'Business Impact': 'Vendor lock-in; limits on tier',
    'Current Approach': 'Resend API',
    'Replace With (Open Source)': 'Postal (MIT), Listmonk (AGPL), or Haraka (MIT). OR run Maddy (GPL-3.0) for both MTA and MDA. All self-host, SPF/DKIM/DMARC supported.',
    'Unlimited-Token Strategy': 'LLM-written transactional copy per tenant brand.',
    Rationale: 'Control + cost',
    Priority: 'Medium',
    'Est. Effort': '2 weeks',
  },
  {
    ID: 'R15',
    Category: 'Replacement',
    Title: 'Vercel → self-hosted Caddy / Nginx deployment',
    Severity: 'L',
    'Area / Component': 'Hosting',
    'Files / Location': 'vercel.json',
    'Root Cause': 'SaaS dependency',
    'Business Impact': 'Cost scales with traffic; limited header control',
    'Current Approach': 'Vercel',
    'Replace With (Open Source)': 'Caddy (Apache 2.0) with automatic HTTPS; Docker + Coolify (Apache 2.0) or Dokku (MIT) for PaaS-lite.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Control, cost, CSP headers',
    Priority: 'Low',
    'Est. Effort': '1 week',
  },
  {
    ID: 'R16',
    Category: 'Replacement',
    Title: 'Stripe → self-hosted billing',
    Severity: 'L',
    'Area / Component': 'Billing',
    'Files / Location': '@stripe/react-stripe-js usage in pages',
    'Root Cause': 'Quick MVP choice',
    'Business Impact': 'Vendor fee; data sovereignty',
    'Current Approach': 'Stripe SaaS',
    'Replace With (Open Source)': 'Lago (AGPL) or Kill Bill (Apache 2.0) for subscription billing. Connect to any payment rail (Adyen, in-house ACH, bank transfer).',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Sovereignty + flexibility',
    Priority: 'Low',
    'Est. Effort': '4 weeks',
  },
  {
    ID: 'R17',
    Category: 'Replacement',
    Title: 'Supabase Storage → MinIO',
    Severity: 'L',
    'Area / Component': 'Storage',
    'Files / Location': 'financial-uploads bucket',
    'Root Cause': 'Coupled to Supabase',
    'Business Impact': 'Lock-in',
    'Current Approach': 'Supabase Storage',
    'Replace With (Open Source)': 'MinIO (AGPL, S3-compatible) OR SeaweedFS (Apache 2.0). Pair with Litestream (Apache 2.0) for backup.',
    'Unlimited-Token Strategy': 'N/A',
    Rationale: 'Portability',
    Priority: 'Low',
    'Est. Effort': '1 week',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SHEET 10 — OPEN-SOURCE STACK AT A GLANCE
// ─────────────────────────────────────────────────────────────────────────────
const stack = [
  { Layer: 'Frontend runtime', 'Current': 'React 18 + Vite (OSS already)', 'Replace With': '— keep —', 'Licence': 'MIT', 'Notes': 'Already OSS' },
  { Layer: 'Frontend state', 'Current': 'TanStack Query (partial)', 'Replace With': 'TanStack Query v5 everywhere', 'Licence': 'MIT', 'Notes': 'Standardise' },
  { Layer: 'Routing state machine', 'Current': 'Hand-written if/else', 'Replace With': 'XState v5', 'Licence': 'MIT', 'Notes': 'Visualisable' },
  { Layer: 'Forms', 'Current': 'react-hook-form', 'Replace With': '— keep — + Zod', 'Licence': 'MIT', 'Notes': '' },
  { Layer: 'UI library', 'Current': 'Radix + shadcn/ui + Tailwind', 'Replace With': '— keep —', 'Licence': 'MIT', 'Notes': 'Already OSS' },
  { Layer: 'Charts', 'Current': 'recharts', 'Replace With': '— keep — or visx', 'Licence': 'MIT', 'Notes': '' },
  { Layer: 'Maps', 'Current': 'react-leaflet', 'Replace With': '— keep —', 'Licence': 'BSD', 'Notes': 'Use self-hosted OSM tiles' },
  { Layer: 'PDF render in browser', 'Current': 'pdfjs-dist', 'Replace With': '— keep —', 'Licence': 'Apache 2.0', 'Notes': '' },
  { Layer: 'DOCX parse in browser', 'Current': 'mammoth', 'Replace With': '— keep —', 'Licence': 'BSD-2', 'Notes': 'Lazy-load' },
  { Layer: 'Error tracking', 'Current': 'none', 'Replace With': 'GlitchTip (self-hosted Sentry OSS)', 'Licence': 'MIT', 'Notes': '' },
  { Layer: 'APM / tracing', 'Current': 'none', 'Replace With': 'SigNoz', 'Licence': 'MIT', 'Notes': 'OTLP native' },
  { Layer: 'Logs', 'Current': 'console', 'Replace With': 'pino → Loki + Grafana', 'Licence': 'MIT / AGPL', 'Notes': '' },
  { Layer: 'Uptime', 'Current': 'none', 'Replace With': 'Uptime Kuma', 'Licence': 'MIT', 'Notes': '' },
  { Layer: 'Status page', 'Current': 'none', 'Replace With': 'Cachet', 'Licence': 'BSD-3', 'Notes': '' },
  { Layer: 'Feature flags', 'Current': 'none', 'Replace With': 'Unleash', 'Licence': 'Apache 2.0', 'Notes': '' },
  { Layer: 'Queue / workflow', 'Current': 'HTTP chain', 'Replace With': 'pg-boss OR Temporal OSS OR River', 'Licence': 'MIT', 'Notes': '' },
  { Layer: 'Cache / pub-sub', 'Current': 'none', 'Replace With': 'Valkey (Redis fork)', 'Licence': 'BSD-3', 'Notes': 'Redis split' },
  { Layer: 'Search', 'Current': 'ILIKE', 'Replace With': 'Typesense OR OpenSearch OR Postgres pg_trgm', 'Licence': 'GPL-3 / Apache 2.0 / PG', 'Notes': '' },
  { Layer: 'Vector DB', 'Current': 'none', 'Replace With': 'pgvector (already available via Postgres)', 'Licence': 'PostgreSQL', 'Notes': 'Reuse DB' },
  { Layer: 'LLM serving', 'Current': 'Vertex Gemini', 'Replace With': 'vLLM or SGLang', 'Licence': 'Apache 2.0', 'Notes': 'OpenAI-compat' },
  { Layer: 'Text LLM (long-ctx)', 'Current': 'Gemini 2.5 Flash', 'Replace With': 'Qwen2.5-1M / Llama 3.3 70B / DeepSeek V3', 'Licence': 'Apache 2.0 / Llama / DeepSeek', 'Notes': 'Check licence per model' },
  { Layer: 'Vision LLM', 'Current': 'Gemini 2.5 Flash', 'Replace With': 'Qwen2.5-VL-72B / Llama 3.2 90B Vision', 'Licence': 'Apache 2.0 / Llama', 'Notes': '' },
  { Layer: 'OCR', 'Current': 'Gemini Vision', 'Replace With': 'Surya OCR + Marker + MinerU', 'Licence': 'GPL / GPL / AGPL', 'Notes': 'Layered' },
  { Layer: 'Table extraction', 'Current': 'Docling (optional)', 'Replace With': 'Docling (self-hosted) + TableTransformer + PaddleOCR-TS', 'Licence': 'MIT / MIT / Apache 2.0', 'Notes': '' },
  { Layer: 'Document layout', 'Current': 'Docling', 'Replace With': 'Docling + Unstructured', 'Licence': 'MIT / Apache 2.0', 'Notes': '' },
  { Layer: 'Grammar-constrained gen', 'Current': 'prompt rules', 'Replace With': 'Outlines / xgrammar / llguidance', 'Licence': 'Apache 2.0', 'Notes': 'Forces valid JSON' },
  { Layer: 'LLM observability', 'Current': 'console', 'Replace With': 'Langfuse OR Phoenix Arize', 'Licence': 'MIT / Elastic 2.0', 'Notes': '' },
  { Layer: 'LLM annotation / eval', 'Current': 'none', 'Replace With': 'Argilla OR Label Studio', 'Licence': 'Apache 2.0', 'Notes': '' },
  { Layer: 'LLM fine-tuning', 'Current': 'none', 'Replace With': 'Axolotl OR LLaMA-Factory', 'Licence': 'Apache 2.0', 'Notes': 'LoRA for domain' },
  { Layer: 'Email', 'Current': 'Resend', 'Replace With': 'Postal OR Listmonk OR Maddy', 'Licence': 'MIT / AGPL / GPL-3', 'Notes': '' },
  { Layer: 'Billing', 'Current': 'Stripe', 'Replace With': 'Lago OR Kill Bill', 'Licence': 'AGPL / Apache 2.0', 'Notes': '' },
  { Layer: 'IdP / SSO / SAML / SCIM', 'Current': 'Google / Azure OAuth', 'Replace With': 'Authentik OR Keycloak', 'Licence': 'MIT / Apache 2.0', 'Notes': '' },
  { Layer: 'Secrets', 'Current': 'Supabase secrets', 'Replace With': 'Infisical OR HashiCorp Vault OSS', 'Licence': 'MIT / MPL-2.0', 'Notes': '' },
  { Layer: 'Policy engine', 'Current': 'JS object literal', 'Replace With': 'Casbin OR Cedar OR Oso', 'Licence': 'Apache 2.0', 'Notes': '' },
  { Layer: 'Rate limiting', 'Current': 'none', 'Replace With': 'Caddy rate-limit OR Traefik OR Kong Gateway OSS', 'Licence': 'Apache 2.0', 'Notes': '' },
  { Layer: 'Web server / TLS', 'Current': 'Vercel', 'Replace With': 'Caddy (auto-HTTPS)', 'Licence': 'Apache 2.0', 'Notes': '' },
  { Layer: 'PaaS-lite', 'Current': 'Vercel + Supabase', 'Replace With': 'Coolify OR Dokku', 'Licence': 'Apache 2.0 / MIT', 'Notes': '' },
  { Layer: 'Object storage', 'Current': 'Supabase Storage', 'Replace With': 'MinIO OR SeaweedFS', 'Licence': 'AGPL / Apache 2.0', 'Notes': '' },
  { Layer: 'DB', 'Current': 'Supabase Postgres', 'Replace With': 'Self-hosted Postgres 16+ + pgvector + pgcrypto', 'Licence': 'PostgreSQL', 'Notes': '' },
  { Layer: 'Pooler', 'Current': 'Supabase pooler', 'Replace With': 'PgBouncer OR PgCat', 'Licence': 'ISC / AGPL', 'Notes': '' },
  { Layer: 'Backups', 'Current': 'Supabase', 'Replace With': 'pgBackRest OR Barman + MinIO', 'Licence': 'MIT / GPL', 'Notes': '' },
  { Layer: 'CDC', 'Current': 'none', 'Replace With': 'Debezium', 'Licence': 'Apache 2.0', 'Notes': '' },
  { Layer: 'Migrations', 'Current': 'Supabase CLI', 'Replace With': 'Sqitch OR Atlas OR Flyway CE', 'Licence': 'MIT / Apache 2.0', 'Notes': '' },
  { Layer: 'Testing (unit)', 'Current': 'none', 'Replace With': 'Vitest + Deno.test', 'Licence': 'MIT', 'Notes': '' },
  { Layer: 'Testing (e2e)', 'Current': 'none', 'Replace With': 'Playwright', 'Licence': 'Apache 2.0', 'Notes': '' },
  { Layer: 'Testing (a11y)', 'Current': 'none', 'Replace With': 'axe-core + Pa11y', 'Licence': 'MPL / LGPL', 'Notes': '' },
  { Layer: 'Testing (property)', 'Current': 'none', 'Replace With': 'fast-check', 'Licence': 'MIT', 'Notes': 'For CAM/budget math' },
  { Layer: 'CI/CD', 'Current': 'Manual', 'Replace With': 'Gitea Actions OR Forgejo Actions OR Drone', 'Licence': 'MIT / Apache 2.0', 'Notes': '' },
  { Layer: 'Monorepo', 'Current': 'none', 'Replace With': 'pnpm workspaces OR Nx OR Turborepo', 'Licence': 'MIT', 'Notes': '' },
];

// ─────────────────────────────────────────────────────────────────────────────
// SHEET 11 — PRIORITIES
// ─────────────────────────────────────────────────────────────────────────────
const priorities = [
  { Phase: 'Immediate (this week)', Item: 'Fix S1, S2, S3 tenancy holes', Owner: 'Sec/Backend', 'Why now': 'Active security risk' },
  { Phase: 'Immediate (this week)', Item: 'Install SigNoz + GlitchTip + OTel SDKs', Owner: 'Platform', 'Why now': 'Blind to prod' },
  { Phase: 'Immediate (this week)', Item: 'Gate in-memory fallback (B5) to DEV mode', Owner: 'Backend', 'Why now': 'Prod errors hidden' },
  { Phase: 'Immediate (this week)', Item: 'Remove extract-lease endpoint (E4)', Owner: 'Backend', 'Why now': 'Regression prevention' },
  { Phase: 'Next 30 days', Item: 'Move doc pipeline to pg-boss / Temporal (A1, P1, R1)', Owner: 'Platform', 'Why now': 'Reliability foundation' },
  { Phase: 'Next 30 days', Item: 'Consolidate duplicate engines (A3, R2)', Owner: 'Domain', 'Why now': 'Financial correctness' },
  { Phase: 'Next 30 days', Item: 'Squash migrations (B1)', Owner: 'DB', 'Why now': 'Bootstrap new envs' },
  { Phase: 'Next 30 days', Item: 'Install rate limiting via Caddy/Traefik (S5)', Owner: 'Platform', 'Why now': 'Abuse protection' },
  { Phase: 'Next 30 days', Item: 'Replace Gemini with vLLM-served Qwen2.5-VL/DeepSeek (R7, E1, E2, E12)', Owner: 'AI', 'Why now': 'Sovereignty + accuracy' },
  { Phase: 'Next 30 days', Item: 'TanStack Query everywhere (F4)', Owner: 'Frontend', 'Why now': 'Stability' },
  { Phase: 'Next 30 days', Item: 'Code splitting (F1, P7)', Owner: 'Frontend', 'Why now': 'Perf' },
  { Phase: 'Next 90 days', Item: 'SSO-SAML + SCIM via Authentik (S12)', Owner: 'Auth', 'Why now': 'Enterprise' },
  { Phase: 'Next 90 days', Item: 'Wire role_definitions + Casbin (O6, R9)', Owner: 'Auth', 'Why now': 'Custom roles' },
  { Phase: 'Next 90 days', Item: 'pgcrypto column encryption (S10)', Owner: 'Sec', 'Why now': 'Compliance' },
  { Phase: 'Next 90 days', Item: 'Audit retention + archival (O9)', Owner: 'Compliance', 'Why now': 'Regulated data' },
  { Phase: 'Next 90 days', Item: 'Playbook + on-call via Grafana OnCall OSS', Owner: 'Ops', 'Why now': 'Ops maturity' },
  { Phase: 'Next 90 days', Item: 'Scale tests at 10k properties', Owner: 'Platform', 'Why now': 'Bottleneck discovery' },
  { Phase: 'Next 90 days', Item: 'GDPR export + purge endpoints (O5)', Owner: 'Compliance', 'Why now': 'Legal' },
  { Phase: 'Next 90 days', Item: 'Signing-authority + budget approval wiring', Owner: 'Domain', 'Why now': 'Product completeness' },
  { Phase: 'Next 90 days', Item: 'Remove every @ts-nocheck (A4)', Owner: 'Backend', 'Why now': 'Quality' },
  { Phase: 'Before enterprise scale', Item: 'SOC 2 Type II via Drata or open audit path', Owner: 'Compliance', 'Why now': 'Sales blocker' },
  { Phase: 'Before enterprise scale', Item: 'Event-sourced financial ledger (R13)', Owner: 'Domain', 'Why now': 'Auditability' },
  { Phase: 'Before enterprise scale', Item: 'Dedicated tenant / region option', Owner: 'Platform', 'Why now': 'Top-tier customers' },
  { Phase: 'Before enterprise scale', Item: 'Blue/green DB migrations + read replicas', Owner: 'DB', 'Why now': 'Zero-downtime' },
  { Phase: 'Before enterprise scale', Item: 'Separate doc pipeline into micro-service', Owner: 'Platform', 'Why now': 'Independent scaling' },
  { Phase: 'Before enterprise scale', Item: 'Feature flags via Unleash', Owner: 'Platform', 'Why now': 'Staged rollout' },
];

// ─────────────────────────────────────────────────────────────────────────────
// Build workbook
// ─────────────────────────────────────────────────────────────────────────────
const wb = XLSX.utils.book_new();

function addIssueSheet(name, rows) {
  const aoa = [COLUMNS, ...rows.map(row)];
  const ws = XLSX.utils.aoa_to_sheet(aoa);
  // Column widths
  ws['!cols'] = [
    { wch: 6 },   // ID
    { wch: 16 },  // Category
    { wch: 55 },  // Title
    { wch: 9 },   // Severity
    { wch: 22 },  // Area
    { wch: 40 },  // Files
    { wch: 45 },  // Root cause
    { wch: 45 },  // Impact
    { wch: 45 },  // Current
    { wch: 70 },  // Replace with
    { wch: 60 },  // Unlimited-token
    { wch: 40 },  // Rationale
    { wch: 18 },  // Priority
    { wch: 14 },  // Effort
  ];
  // Freeze header row
  ws['!freeze'] = { xSplit: 0, ySplit: 1 };
  XLSX.utils.book_append_sheet(wb, ws, name);
}

// Sheet 1 — Summary
{
  const ws = XLSX.utils.aoa_to_sheet(summaryRows);
  ws['!cols'] = [{ wch: 30 }, { wch: 110 }];
  XLSX.utils.book_append_sheet(wb, ws, '1. Summary');
}

// Issue sheets
addIssueSheet('2. Architecture', architecture);
addIssueSheet('3. Security', security);
addIssueSheet('4. Performance', performance);
addIssueSheet('5. AI Extraction OCR', ai);
addIssueSheet('6. Frontend', frontend);
addIssueSheet('7. Backend DB', backend);
addIssueSheet('8. Auth Obs Compliance', observability);
addIssueSheet('9. Replace Redesign', replace);

// Stack sheet
{
  const stackCols = ['Layer', 'Current', 'Replace With', 'Licence', 'Notes'];
  const aoa = [stackCols, ...stack.map((s) => stackCols.map((c) => s[c] ?? ''))];
  const ws = XLSX.utils.aoa_to_sheet(aoa);
  ws['!cols'] = [{ wch: 26 }, { wch: 28 }, { wch: 55 }, { wch: 28 }, { wch: 30 }];
  ws['!freeze'] = { xSplit: 0, ySplit: 1 };
  XLSX.utils.book_append_sheet(wb, ws, '10. OSS Stack');
}

// Priorities sheet
{
  const pCols = ['Phase', 'Item', 'Owner', 'Why now'];
  const aoa = [pCols, ...priorities.map((p) => pCols.map((c) => p[c] ?? ''))];
  const ws = XLSX.utils.aoa_to_sheet(aoa);
  ws['!cols'] = [{ wch: 26 }, { wch: 70 }, { wch: 18 }, { wch: 45 }];
  ws['!freeze'] = { xSplit: 0, ySplit: 1 };
  XLSX.utils.book_append_sheet(wb, ws, '11. Priorities');
}

// Issue counts
const totals = {
  Architecture: architecture.length,
  Security: security.length,
  Performance: performance.length,
  AI: ai.length,
  Frontend: frontend.length,
  'Backend/DB': backend.length,
  'Auth/Obs': observability.length,
  'Replace/Redesign': replace.length,
  'Stack items': stack.length,
  Priorities: priorities.length,
};

XLSX.writeFile(wb, OUT_PATH);
console.log('Wrote', OUT_PATH);
console.log('Row counts:', totals);
console.log('Total issues:', architecture.length + security.length + performance.length + ai.length + frontend.length + backend.length + observability.length + replace.length);
