// @ts-nocheck
export const PACKAGE_RUNTIME_ERROR_CODES = {
  PACKAGE_MODE_REQUIRES_CLAIMS_LEDGER: "PACKAGE_MODE_REQUIRES_CLAIMS_LEDGER",
  PACKAGE_ACTIVE_REQUIRES_CLAIMS_ACTIVE: "PACKAGE_ACTIVE_REQUIRES_CLAIMS_ACTIVE",
  PACKAGE_MODE_CONFIGURATION_INVALID: "PACKAGE_MODE_CONFIGURATION_INVALID",
  PACKAGE_ACTIVE_GENERATION_MISMATCH: "PACKAGE_ACTIVE_GENERATION_MISMATCH",
  PACKAGE_EXTRACTION_RUN_MISMATCH: "PACKAGE_EXTRACTION_RUN_MISMATCH",
  CLAIM_LEDGER_MISSING: "CLAIM_LEDGER_MISSING",
  CLAIM_PROJECTION_MISSING: "CLAIM_PROJECTION_MISSING",
  CLAIM_PROJECTION_FAILED: "CLAIM_PROJECTION_FAILED",
  CLAIM_PROJECTION_STALE_GENERATION: "CLAIM_PROJECTION_STALE_GENERATION",
  PACKAGE_PROFILE_MISSING: "PACKAGE_PROFILE_MISSING",
  PACKAGE_PROFILE_AMBIGUOUS: "PACKAGE_PROFILE_AMBIGUOUS",
  PACKAGE_MEMBERSHIP_MISSING: "PACKAGE_MEMBERSHIP_MISSING",
  PACKAGE_MEMBERSHIP_AMBIGUOUS: "PACKAGE_MEMBERSHIP_AMBIGUOUS",
  PACKAGE_RESOLUTION_MISSING: "PACKAGE_RESOLUTION_MISSING",
  PACKAGE_PROJECTION_MISSING: "PACKAGE_PROJECTION_MISSING",
  PACKAGE_COMPATIBILITY_NOT_PERSISTED: "PACKAGE_COMPATIBILITY_NOT_PERSISTED",
  PACKAGE_RUNTIME_FAILED: "PACKAGE_RUNTIME_FAILED",
} as const;

export class PackageRuntimeError extends Error {
  errorCode: string;

  constructor(errorCode: string, message = errorCode) {
    super(message);
    this.name = "PackageRuntimeError";
    this.errorCode = errorCode;
  }
}
