-- Repairs audit_logs_source_check to include 'rpc', discovered when
-- approve_and_lock_budget's own audit_logs insert (source: 'rpc' --
-- 20260904000000_budget_approval_signoff.sql, step I) hit
-- `new row for relation "audit_logs" violates check constraint
-- "audit_logs_source_check"` on its very first live execution.
--
-- 'rpc' is not a one-off typo: it is the same, deliberately-used audit
-- source value in at least five other CAM RPCs (grep across
-- supabase/migrations for source: 'rpc' -- 20269900000025_cam_phase4b_
-- posting.sql, 20269900000026_cam_real_property_validation_gate.sql,
-- 20269900000027_verify_real_property_gate_rpc.sql,
-- 20269900000028_cam_legacy_migration.sql), distinguishing an audit event
-- generated directly by a database RPC from one generated by edge-function
-- orchestration logic ('edge_function'). The CHECK constraint was simply
-- never widened to match when this convention was introduced -- the
-- correct fix is adding the value, not changing five-plus already-correct
-- RPCs to misreport their own provenance.
ALTER TABLE public.audit_logs
  DROP CONSTRAINT IF EXISTS audit_logs_source_check;

ALTER TABLE public.audit_logs
  ADD CONSTRAINT audit_logs_source_check
  CHECK (source = ANY (ARRAY['frontend'::text, 'edge_function'::text, 'webhook'::text, 'system'::text, 'rpc'::text]));
